- board/piksiv3/rootfs-overlay/etc/init.d/S10mdev
- board/piksiv3/rootfs-overlay/etc/init.d/S99coldplug
Moves the coldplug part of the buildroot mdev init script to a later init script so that firmware may be copied to `/lib/firmware` before `zynq_remoteproc` is probed.
> Coldplug modules after loading firmware

- board/piksiv3/post_image.sh
- package/uboot_custom/uboot_custom.mk
Updates post image script to set additional version information.
E.g.
```
Image set header:
Name:         Piksi Buildroot 6d286b5
Version:      00000000
Timestamp:    57e19df5
Hardware:     00000001
Seq Num:      00000000
Image descriptor 0:
Type:         00000002
Name:         U-Boot 6911a76 for zynq board
Version:      00000000
Timestamp:    57e19dc3
Load Addr:    00000000
Entry Addr:   00000000
Data Offset:  00000900
Data Size:    0000eb97
Data CRC:     0f38fb72
```
TODO:
> Set additional version information

- board/piksiv3/piksiv3_evt1.dts
- board/piksiv3/piksiv3_evt2.dts
- board/piksiv3/piksiv3_microzed.dts
Prevents disabling of clocks unused by Linux (GPIO, SPI, etc.)
> Add clk_ignore_unused to bootargs

- .gitignore
- .travis.yml
- Dockerfile
- README.md
- board/piksiv3/post_build.sh
- board/piksiv3/post_image.sh
- board/piksiv3/rootfs-overlay/etc/init.d/S75dev_boot
- build.sh
- configs/piksiv3_defconfig
- fetch_firmware.sh
**What:**
We currently build two different system images, production (prod) and development (dev). In the development configuration the firmware and FPGA images are loaded either from the SD card or from the network over TFTP. However in the production configuration we want these images to be incorporated into the system image, and any images present on the SD card or network should be ignored. This pull request implements downloading a specified set of firmware and FPGA images and incorporating them into the system image such that they are used in the production configuration.
**How:**
A script `fetch_firmware.sh` is added which downloads the firmware images for the various hardware configurations from the S3 artifacts bucket. These images are specified by a version string in the script. …
> Download firmware from S3 and incorporate into Linux system images

- board/piksiv3/rootfs-overlay/etc/init.d/S75dev_boot
OS X tftpd doesn't like the absolute path. The linux one should work with either.
cc: @jacobmcnamee
> Fix firmware TFTP load from OS X tftpd

- board/piksiv3/device_table.txt
- board/piksiv3/rootfs-overlay/etc/init.d/S90monit
- board/piksiv3/rootfs-overlay/etc/monitrc
**What:**
The operation of the device relies on several Linux daemons to be running. Despite our best efforts there is a possibility these daemons might crash. To increase the robustness of the system we should monitor these processes and restart them if they die.
**How:**
We use Monit for monitoring (buildroot package brought in in #53). This PR adds Monit to our `init.d` and add a Monit configuration file that points it at the `pid` files and start / stop scripts for the various daemons created by `init`.
We also configure Monit to expose its web dashboard on its default port of 2812 with username and password `piksi`. This makes it easy to see what processes are running and some basic CPU and memory stats.
**Testing:**
- Note, this testing revealed a flaw in `sbp_settings_daemon`, it …
> Process monitoring

- board/piksiv3/post_image.sh
Deleting `rootfs.cpio` from `buildroot/output/images` can cause incremental builds to fail.
/cc @fnoble @swift-nav/firmware
> Do not delete files from output images folder

- board/piksiv3/piksiv3_microzed.dts
- board/piksiv3/piksiv3_prod.dts
- package/uboot_custom/uboot_custom.mk
Supersedes #51 
- Serial stdout disabled by default in device tree, re-enable via bootarg `console=ttyPS1,115200`
- U-Boot `dev` config updated to enable stdout via bootarg
TODO:
> Turn off serial console output

- .travis.yml
- board/piksiv3/post_image.sh
- package/uboot_custom/uboot_custom.mk
Changes to support https://github.com/swift-nav/u-boot-xlnx/pull/20.
- Generate image set for `dev` config with U-Boot and FPGA images
- Merge `dev` and `prod` output folders
TODO:
> Use image table boot for dev config

- package/zmq_router/src/zmq_router_sbp.c
Replace #60 from the swift-nav repo
> zmq_router: Don't filter settings read reply messages.

- board/piksiv3/post_image.sh
Image header name field is limited to 32B.
> Remove 'Piksi Buildroot' from image headers

- board/piksiv3/rootfs-overlay/etc/init.d/S84upgrade_tool
/cc @gsmcmullin @jacobmcnamee 
This works reliably on prod for me after adding the sleep.
- I changed the default warn level to warn (as that is the default level on the console and I wouldn't want to hide the messages)
- I also got rid of deleting the file and rebooting as it wasn't very user friendly.  This way, the user knows things were completed and isn't left guessing what happened.  Also the user would be able to take the flash drive and update another device afterwards.
- I lastly echoed the real name of the file
In the future we would like to:
- Blink PV led during upgrade
- Blink PV led afterwards differently
- make the serial output useful to someone in a plain text terminal as well as piksi console (maybe add some line breaks or something)
- Compare software versions on the …
> Add sleep to upgrade init script, don't delete file or reboot afterwards

- board/piksiv3/rootfs-overlay/etc/init.d/adapter_uart.inc.sh
Fixes gserial issue that results in USB port not working and the following error:
`/etc/init.d/S83zmq_adapter_gserial: /etc/init.d/S83zmq_adapter_gserial: source: line 6: can't open '/etc/init.d/adapter_uart.inc.sh'`
cc: @denniszollo
> GSerial fix

- board/piksiv3/rootfs-overlay/etc/init.d/usb_upgrade.sh
should solve:
https://github.com/swift-nav/piksi_v3_bug_tracking/issues/190
We do need to consider weird cases (usb hubs, other sda devices plugged in); any thoughts?
**Testing**
/cc @gsmcmullin @cbeighley @zakaswift
> Allow any /sda/* device to hold the FW

- fetch_firmware.sh
Accomodates https://github.com/swift-nav/piksi_firmware_private/pull/462.
> Update FW ptr to latest v1.0.0-release branch (release)

- board/piksiv3/piksiv3.dtsi
- board/piksiv3/piksiv3_microzed.dts
- board/piksiv3/piksiv3_prod.dts
- fetch_firmware.sh
Increase firmware memory allocation from 32MB to 64MB.
TODO:
/cc @swift-nav/firmware @benjamin0
> Increase firmware memory allocation (master)

- board/piksiv3/piksiv3.dtsi
- board/piksiv3/piksiv3_microzed.dts
- board/piksiv3/piksiv3_prod.dts
- fetch_firmware.sh
Release version of https://github.com/swift-nav/piksi_buildroot/pull/101.
> Increase firmware memory allocation (release)

- package/libsbp_zmq/src/sbp_zmq.c
- package/piksi_system_daemon/src/main.c
UART port mode and baud rate settings values were not being saved due to bugs in `piksi_system_daemon`.
For baud rate, ignoring `SIGCHLD` prevented `system()` from obtaining the exit status of the child process, causing `system()` to return an error and the setting to not be committed. The requested command generally still executed.
For port mode, the setting was erroneously never committed.
Resolves https://github.com/swift-nav/piksi_v3_bug_tracking/issues/197
TODO:
> Fix UART port mode and baud rate settings (master)

- board/piksiv3/patches/linux/0002-tty-serial-xuartps-Implement-automatic-RTC-CTS-flow-.patch
- package/piksi_system_daemon/src/main.c
- package/zmq_adapter/src/zmq_adapter_file.c
- Configure TTYs in `piksi_system_daemon` using `tcsetattr()` with `TCSANOW` (`stty` uses `TCSADRAIN`, which waits for pending transmit data to be flushed)
- Use enum for baud rate
- Flow control support (setting + kernel patch)
> Configure UARTs in piksi_system_daemon, implement HW flow control

- board/piksiv3/piksiv3.dtsi
- board/piksiv3/rootfs-overlay/etc/init.d/S95watchdog_disable
- package/uboot_custom/uboot_custom.mk
- Update U-Boot to enable watchdog during boot for prod config
- Add init script to disable watchdog in Linux
TODO:
> Minimal watchdog support

- .travis.yml
- Dockerfile
- Makefile
- Remove buildroot build commands from dockerfile
- Add docker targets to makefile:
- `docker-setup` - runs `docker build` to prepare docker image
- `docker-make-image` - runs `make image` inside of docker container
- `docker-run` - starts an interactive docker container
- Mount directories inside docker container:
- `/piksi_buildroot` (source directory) - backed by host directory. 
- `/piksi_buildroot/buildroot` (build directory) - backed by persistent docker volume. This avoids a significant slowdown (at least on OSX), but anything written here will not be visible on the host filesystem
- `/piksi_buildroot/buildroot/output/images` (output directory) - backed by host directory
- Update `.travis.yml`
Example:
```shell
make docker-setup
make docker-make-image
make docker-run
cd buildroot …
```
> Support incremental docker builds

- fetch_firmware.sh
Fixes issue where current S3 firmware fetch setup for build-root image
build is failing because of some NAP file renaming on S3.
/cc @denniszollo @wltr @jacobmcnamee
> Fix S3 firmware fetch: update firmware version and NAP version.

- host_tests/rotating_logger/run_rotating_logger_test.cc
- package/rotating_zmq_logger/src/rotating_logger.cc
- package/rotating_zmq_logger/src/rotating_logger.h
- package/rotating_zmq_logger/src/rotating_zmq_logger.cc
Drive would not unmount properly if USB pulled out. This switches to unbuffered writes and waits to start new file to fix issue.
> Updated to avoid locking drive

- Dockerfile
- Allows running `make menuconfig` inside of Docker container for buildroot configuration
- Mercurial to acquire some buildroot packages, e.g. Eigen.
> Add packages to Dockerfile

- package/piksi_system_daemon/src/main.c
Resolves issue with the `dev` config where an initial manual configuration causes errors when `piksi_system_daemon` tries to reconfigure:
```
ifdown: interface eth0 not configured
ip: RTNETLINK answers: File exists
```
The problem appears to be that old routes / IP addresses are not cleared by `ifdown` when the interface was not brought up with `ifup`. Using `ifdown -f` should fix this.
> Use ifdown -f

- package/libpiksi/libpiksi/src/sbp_zmq_rx.c
Addresses https://github.com/swift-nav/piksi_v3_bug_tracking/issues/369
> Fixed pollitem_init to use libzmq void* socket

- package/piksi_system_daemon/src/cellmodem.c
If the cellmodem process gets killed off, it should always have its pid zero'd. Otherwise, future configuration changes can end up HUP'ing unrelated pids.
/cc @gsmcmullin @jacobmcnamee
> Zero pppd pid

- package/rpmsg_piksi/src/rpmsg_piksi.c
Maximum length for `rpmsg_sendto()` is `RPMSG_BUF_SIZE - sizeof(struct rpmsg_hdr)` = `512 - 16`. Log an error and return success if this value is exceeded.
/cc @swift-nav/firmware @mfine
> rpmsg_piksi: truncate TX messages to the maximum data size

- package/piksi_system_daemon/src/main.c
Fix issue where USB0 TTY was not configured (in particular `onlcr` was not cleared).
Resolves https://github.com/swift-nav/piksi_v3_bug_tracking/issues/356
> Configure USB0 TTY

- package/libpiksi/libpiksi/src/sbp_zmq_rx.c
Release version of https://github.com/swift-nav/piksi_buildroot/pull/194.
> Cherry pick Jonathan's fix for pollitem_init to use libzmq void socket

- package/sbp_protocol/src/filter_sbp.c
- package/sbp_protocol/src/framer_sbp.c
- package/zmq_adapter/src/Makefile
- package/zmq_adapter/src/filter.c
- package/zmq_adapter/src/framer.c
- package/zmq_adapter/src/framer_none.c
- package/zmq_adapter/src/protocols.c
- package/zmq_adapter/src/zmq_adapter.c
- package/zmq_adapter/src/zmq_adapter.h
- package/zmq_adapter/src/zmq_adapter_file.c
- package/zmq_adapter/src/zmq_adapter_stdio.c
- package/zmq_adapter/src/zmq_adapter_tcp_listen.c
- Retry on EINTR for `zmsg_send()` and `zmsg_recv()`
- Properly handle data buffered in framer
- Fix minor warnings
- Use `syslog` instead of `printf`
- `stdin` / `stdout` support
- Startup delay option (useful when sending files)
TODO:
> ZMQ adapter improvements

- package/piksi_system_daemon/src/main.c
Go back to the way it was to v1.0.11
It is convenient to have both outputs possible out-of-the box.  This way the documents are also consistent for 1.0.11 and the release.
> Update default portmode for TCP Server 1 to NMEA

- package/zmq_router/src/zmq_router_load.c
`yaml_parser_delete()` can cause asserts if provided an uninitialized parser struct.
> ZMQ router: fix possible assert if config file does not exist

- .travis.yml
- package/sbp_rtcm3_bridge/sbp_rtcm3_bridge/test/Makefile
- package/standalone_file_logger/standalone_file_logger/test/Makefile
- Add `set -o pipefail` to Travis commands
- Fix multiple definition of main() for test executables with `-z muldefs`
>The exit status of a pipeline is the exit status of the last command in the pipeline, unless the pipefail option is enabled
This was preventing the build from failing when it should have.
/cc @swift-nav/firmware @mfine
> Fix Travis builds

- package/sbp_rtcm3_bridge/src/sbp_rtcm3.c
- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
This is to fix the following defect
https://github.com/swift-nav/piksi_v3_bug_tracking/issues/435
where the length of the sbp message was being set to one when we the final sbp message was of full length. This was showing up on the novatel as it often dropped to tracking 7 sats, but CORS stations rarely did
@pgrgich
> Encode MAX size when appropriate

- package/libnetwork/src/libnetwork.c
Protect against the undefined `TCP_USER_TIMEOUT` - currently breaking on host builds.
> Don't do anything if tcp option is not defined

- board/piksiv3/rootfs-overlay/etc/init.d/S75dev_boot
We'd like to copy over a config on boot - it provides a more reliable mechanism for ensuring configuration on startup then other means, especially sending sbp settings messages on startup.
/cc @axlan @jacobmcnamee @denniszollo
> Copy over config.ini with boot files

- board/piksiv3/rootfs-overlay/etc/init.d/reset2defaults.sh
- board/piksiv3/rootfs-overlay/etc/init.d/usb_upgrade.sh
The reset2defaults was only working when a firmware file existed on flash drive due to my typo.  This should fix.
> Fix script typo on usb-drive functions: reset2defaults and usb_upgrade.

- package/piksi_system_daemon/src/Makefile
- package/piksi_system_daemon/src/main.c
- package/piksi_system_daemon/src/ports.c
- package/piksi_system_daemon/src/ports.h
- Move ports handling into a separate file
- Add "disabled" port mode
- Check exit status of forked `zmq_adapter` processes
- Specify default mode for each port
- Disable TCP client ports by default
TODO: 
/cc @swift-nav/firmware @denniszollo
> Port improvements

- package/piksi_system_daemon/src/main.c
Addresses https://github.com/swift-nav/piksi_v3_bug_tracking/issues/407
The issue is the ifup command triggers Udhcpc which blocks the system call
> make ifup run in background to prevent blocking setting callback

- package/piksi_system_daemon/src/Makefile
- package/piksi_system_daemon/src/async-child.c
- package/piksi_system_daemon/src/async-child.h
- package/piksi_system_daemon/src/main.c
- package/piksi_system_daemon/src/ports.c
This adds a new module to piksi_system_daemon for management of asynchronous child processes with piped output.
A function `async_spawn` is provided to spawn such a process, and it takes callback function pointers for notification of the child's standard output and exit status.  The output is assumed to be text, and is split on newlines.  Both callback functions will be called from the zmq loop provided.  If needed in future it would be simple to add pipes for the child's stdin and stderr.
Internally, a pipe is used to syncronise the SIGCHLD handler where the child is reaped with the zmq loop from which the exit notification callback must be called.  I couldn't find a simpler safe way to do this.
This new mechanism is used for the SBP command implementation, instead of `popen`/`pclose` …
> piksi_system_daemon: Add async-child module.

- package/piksi_system_daemon/src/ports.c
- package/zmq_adapter/src/zmq_adapter.c
- package/zmq_adapter/src/zmq_adapter_file.c
- package/zmq_adapter/src/zmq_adapter_tcp_connect.c
- package/zmq_adapter/src/zmq_adapter_tcp_listen.c
A proposed solution for swift-nav/firmware_team_planning#270.
Options are added to `zmq_adapter` to set the port in non-blocking mode and/or specify an output queue size limit for tty devices.
These options are added to `piksi_system_daemon` for instances of `zmq_adapter` on the uarts and gadget serial port.  This prevents excessive buffering of output data when port writes are blocked by flow control.
Stale data is still left in the output queue, but the amount is limited.  Flushing the queue with `tcflush` was not successful.
> Limit output buffering on physical ports

- package/factory_data_tool/src/factory_data_tool.c
- package/uboot_custom/uboot_custom.mk
Depends on https://github.com/swift-nav/u-boot-xlnx/pull/35 , uboot SHA must be updated when that's merged.
See also:
https://github.com/swift-nav/piksi_firmware_private/pull/852
> updated uboot for factory hardware revision

- .travis.yml
This is an attempt to prevent builds whose files are labeled without any tag: 
i.e.
> .travis.yml: Make sure to fetch tags before building buildroot images

- package/piksi_system_daemon/src/async-child.c
- package/piksi_system_daemon/src/async-child.h
- package/piksi_system_daemon/src/cellmodem.c
- package/piksi_system_daemon/src/cellmodem.h
- package/piksi_system_daemon/src/main.c
Respawn pppd if it dies.
Add debug option to forward pppd stdout over sbp log.
> piksi_system_daemon: Use async-child to manage pppd.

- package/zmq_adapter/src/zmq_adapter.c
- package/zmq_adapter/src/zmq_adapter_file.c
Opening for read is blocking on a named pipe, so the zmq_adapter spawned for skylark was never getting to the main loop.
> Open pipes for O_RDWR (fix Skylark)

- package/gnss_convertors/gnss_convertors.mk
- package/librtcm/librtcm.mk
- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
This fixes a problem where the ns field wasn't being used to calculate the glonass TOD which lead to a 1s error in the leap second calculations.
> Fix leap sec rounding from ns field

- package/sbp_rtcm3_bridge/src/sbp.h
- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Don't set the time parameters without checking for message validity first
@mfine
> only set time parameters on valid time messages

- board/piksiv3/patches/linux/0003-gserial-Drain-tty-output-buffer-when-USB-is-connecte.patch
- package/zmq_adapter/src/zmq_adapter.c
Test fix for: https://github.com/swift-nav/piksi_v3_bug_tracking/issues/570
- Kill zmq_adapter when the first forks dies.
- Drain tty output buffer when USB cable is connected.
> USB Gadget fixes

- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
One thing that might be contributing to the sbp_rtcm3_bridge crashing, if we get SBP time message in before it's fully initialized.
> Init sbp_rtcm3_bridge state first

- package/gnss_convertors/gnss_convertors.mk
- package/sbp_rtcm3_bridge/src/Makefile
- Add symbols to sbp_rtcm3_bridge build
- Update gnss-convertors release version to get changes to stop crashes.
> Changes for sbp_rtcm3_bridge crash issue

- package/libnetwork/docs/about.md
- package/ntrip_daemon/docs/README.md
A few doc improvements for libnetwork and the ntrip_daemon, does not need to go to release 1.2.0.
> libnetwork & ntrip doc improvements

- package/piksi_system_daemon/src/ports.c
> Kill usb0 zmq_adapter in case forks are still alive. 

- package/ntrip_daemon/docs/README.md
Need to enclose the diagram in a code block so it renders correctly.
> Make ntrip network diagram readable on github.com

- release_notes.txt
First cut at release notes:
I'm not sure if we are going to merge in the text only release notes as we had initially decided to replace the text release notes we made for v1.1 and v1.2 with the pdf version to have only one source of information.
But, I realized that creating the text only release notes was a useful exercise in order to better create the formatted release notes with additional exposition.
/cc @switanis @akshaybandiwdekar @robhranac
> V1.2 release notes draft

- package/piksi_system_daemon/src/ports.c
- package/piksi_system_daemon/src/whitelists.c
My task from triage meeting.
Requires console testing and SBP2RINEX testing before merging; both should work with a file recorded over UART1.
Will break HITL since HITL probably only uses the ECEF messages and is connected over UART1. @axlan
> Update UART1 whitelist for usability.

- Dockerfile
- Makefile
+ Use `--rm` so that a new container isn't created every time we run a make command.
+ Add a few helpful tools to the build image: ag, and vim.
+ Add `docker-pkg-%` family of commands for rebuilding individual packages.
+ Name the docker image that's used in the `docker-run` target so that files can be easily copied out of the volume using `docker cp`.
> Docker usability improvements

- board/piksiv3/post_image.sh
Incremental builds will fail when switching from master to v1.2.0-release since there are 2 directories that match the search criteria.
> Find a specific uboot to use

- package/piksi_system_daemon/src/ports.c
- package/zmq_adapter/src/zmq_adapter.c
I have witnessed a situation where several adapters on UART0 were running.
Some of them were running as SBP, others as RTCM.
It appears that the proble is that the zmq_adapter exits when receiving SIGIO, which is unhandled.
> Ignore SIGIO

- board/piksiv3/rootfs-overlay/etc/init.d/S75dev_boot
This change would enable custom tests as part of HITL. Some examples:
* Test UART loopback
* Test file logger throughput
* Test changing settings
This script could copy down other files and add the scripts to different init levels if needed
> Run optional init script

- board/piksiv3/piksiv3.dtsi
- board/piksiv3/piksiv3_microzed.dts
- board/piksiv3/piksiv3_prod.dts
*NOTE:* THIS WILL BREAK FIRMWARE COMPATIBILITY.
This PR makes the necessary buildroot memory adjustments in order to work with the new MMU table.
**Dependencies:**
> Adjust memory for new firmware MMU table

- package/zmq_adapter/src/zmq_adapter_tcp_connect.c
Fix for https://github.com/swift-nav/firmware_team_planning/issues/377.
+ Configure the TCP socket that zmq_adapter opens up with keep-alive so that it'll recover (quicker) when the network stalls.
+ Add address resolution to the `addr_parse` helper so that TCP connections can use a DNS name instead of just an IP address.
> Allow TCP client to recover after network stalls

- package/zmq_adapter/src/zmq_adapter_udp_connect.c
This should allow a user to set 192.168.1.255 address for udp broadcast on the UDP Client.
It doesn't allow UDP Broadcast on the UDP Server.
/cc @cbeighley @srossel
> Allow UDP Broadcast Release

- package/piksi_system_daemon/piksi_system_daemon/src/whitelists.c
This PR adds 2 messages to the white list:
Klobuchar ionospheric parameters message (MT 144)
GLONASS phase biases message necessary for GLONASS fixing (MT 117)
The impact of both message on bandwidth is expected to be negligible.
Merge of ***RELEASE***
@cbeighley
> [Relase] Update of whitelist with iono and GLO phase biases

- package/piksi_system_daemon/piksi_system_daemon/src/whitelists.c
This PR adds 2 messages to the white list:
- Klobuchar ionospheric parameters message (MT 144)
- GLONASS phase biases message necessary for GLONASS fixing (MT 117)
The impact of both message on bandwidth is expected to be negligible.
Merge of *MASTER*
@cbeighley
> Update of whitelist with iono and GLO phase biases

- board/piksiv3/rootfs-overlay/etc/ppp/options
- package/piksi_system_daemon/piksi_system_daemon/src/Makefile
- package/piksi_system_daemon/piksi_system_daemon/src/cellmodem.c
- package/piksi_system_daemon/piksi_system_daemon/src/cellmodem.h
- package/piksi_system_daemon/piksi_system_daemon/src/cellmodem_inotify.c
- package/piksi_system_daemon/piksi_system_daemon/src/cellmodem_probe.c
- package/piksi_system_daemon/piksi_system_daemon/src/cellmodem_probe.h
- Remove modem dev and type settings
- When new tty devices are found they are probed with AT command for
modem detection
- Modem make/model/revision/serial number are logged over SBP
- GSM/CDMA is autodetected so the correct connect script can be used
> Auto-detect and log cell modem presence

- package/piksi_system_daemon/piksi_system_daemon/src/whitelists.c
Support the forwarding of GLO biases by default.
/cc @scarcanague
> Update the whitelist for UART0 to support GLO biases.

- .travis.yml
+ Change the naming of what's uploaded for the SDK build so that it can
be put into the same folder as the other build logs
+ Add back PRODUCT_VERSION/PRODUCT_REV so it's obvious that they're
arguments to the publish.sh script
+ Remove the comment.sh script from the SDK example build
cc: @mfine
> Rename sdk build output, don't push build comment to GH

- Makefile
- README.md
- publish.sh
+ Addresses https://github.com/swift-nav/firmware_team_planning/issues/412
+ Don't accidentally pre-populate buildroot dir.  This will cause the `git submodule update` command to fail.
+ Fix fetch_firmware.sh to not try to use a public-read puts.
> [Release 1.3.x] don't pre-populate the buildroot dir, fix publish.sh

- package/libnetwork/src/libnetwork.c
This is a first pass addressing https://github.com/swift-nav/piksi_v3_bug_tracking/issues/921 along with some input from @mfine and @LanceAndre as summarized below:
This PR covers:
* Curl reported error and http repsonse codes (failed connections, bad creds or url)
* Exposing this activity to the user via Swift Console via `sbp_log`
This PR does NOT cover:
* NTRIP protocol level issues that may arise (No NTRIP caster found, NMEA GGA not set - possibly related to https://github.com/swift-nav/piksi_buildroot/pull/444, RTCM message type 16/36/1029 reporting)
*Details*
This is not much more than adding curl error string reporting as well as http response code info logging via `sbp_log`, where previously these were only sent to `piksi_log` (`vsyslog`). Nevertheless this covers a variety of …
> Interim NTRIP connectivity logging improvements

- board/piksiv3/patches/ntp/0001-nmea-ignore-build-time.patch
- board/piksiv3/rootfs-overlay/etc/init.d/S45zmq_adapter_gps0
- board/piksiv3/rootfs-overlay/etc/ntp.conf
- board/piksiv3/rootfs-overlay/etc/ntp.conf.gps
- board/piksiv3/rootfs-overlay/etc/ntp.conf.gpsntp
- board/piksiv3/rootfs-overlay/etc/ntp.conf.ntp
- package/piksi_system_daemon/piksi_system_daemon/src/main.c
This provides UTC from our navigation solution as a reference clock to set the Linux system time.
- Start a new zmq_adapter to connect NMEA stream and use socat to link to pty at /dev/gps0
- Add NMEA reference clock to ntpd configuration
- Patched NTP to allow a system time older than it's build time in NMEA driver
- Add a setting to select system time source for cases when NTP and GPS time are available, but different.
For https://github.com/swift-nav/firmware_team_planning/issues/290
> Connect NMEA output to ntpd via pty linked at /dev/gps0

- board/piksiv3/rootfs-overlay/etc/init.d/S85network_poll
- board/piksiv3/rootfs-overlay/etc/init.d/network_poll.sh
Periodically check for Internet connectivity by pinging public DNS servers.
Network status is written to `/var/run/network_available` for use by other processes.
While network is down, an SBP warning will be logged periodically with the text "No route to Internet"
For Duro Cell Modem solution S1 & S2, task https://github.com/swift-nav/firmware_team_planning/issues/429
Works with https://github.com/swift-nav/piksi_buildroot/pull/452 for LED changes.
>  Poll for network state with ping

- package/health_daemon/src/baseline_monitor.c
- package/health_daemon/src/health_monitor.c
- package/health_daemon/src/health_monitor.h
Conversion from mm to m was needed for correct
evaluation of the threshold. The timer callback
was added to build in a 1Hz rate limit on alerts.
Addresses swift-nav/piksi_v3_bug_tracking#986
> Fix baseline calculation for threshold warning

- package/llvm_obfuscator/llvm_obfuscator.hash
- package/llvm_obfuscator/llvm_obfuscator.mk
- package/piksi_ins_ref/piksi_ins_ref.mk
Fix for https://github.com/swift-nav/firmware_team_planning/issues/432
+ Bring in v12 of llvm-obfuscator-arm which fixes compatibility issues with the default buildroot toolchain
+ Sync /lib from the default toolchain's sysroot dir (this pulls in libuuid.so needed for linking against czmq)
+ Bring v9 of piksi_ins_ref, which adds a test checking that linking against czmq works
> llvm_obfuscator: update to v12, check linking of czmq

- package/piksi_leds/src/led_adp8866.c
- package/piksi_leds/src/manage_led.c
Also wait for firmware to boot before configuring LED controllers.  LED reset signal is driven by firmware on a GPIO.  Moving this to Linux is inconvenient, as the firmware needs the GPIO controller for other purposes.
> piksi_leds: Exit on init failures.

- package/llvm_obfuscator/llvm_obfuscator.hash
- package/llvm_obfuscator/llvm_obfuscator.mk
- package/piksi_ins_ref/piksi_ins_ref.mk
Fix for https://github.com/swift-nav/firmware_team_planning/issues/432
+ Bring in v12 of llvm-obfuscator-arm which fixes compatibility issues with the default buildroot toolchain
+ Sync /lib from the default toolchain's sysroot dir (this pulls in libuuid.so needed for linking against czmq)
+ Bring v9 of piksi_ins_ref, which adds a test checking that linking against czmq works
> llvm_obfuscator: update to v12, check linking of czmq [v1.4]

- package/sbp_protocol/src/sbp_router.yml
Now that we implement sending a settings write response, we need to
allow the response to be sent to SBP_PORT_EXTERNAL so it can make it's
way to the console.
> Allow settings write response to go to SBP_PORT_EXTERNAL

- board/piksiv3/rootfs-overlay/etc/init.d/network_poll.sh
- package/piksi_system_daemon/piksi_system_daemon/src/ntrip.c
- package/piksi_system_daemon/piksi_system_daemon/src/skylark.c
Fix for https://github.com/swift-nav/piksi_v3_bug_tracking/issues/996
> Only do the "no internet" check if NTRIP/Skylark is enabled

- package/health_daemon/src/Makefile
- package/health_daemon/src/glo_bias_monitor.c
- package/health_daemon/src/glo_bias_monitor.h
- package/health_daemon/src/glo_health_context.c
- package/health_daemon/src/glo_health_context.h
- package/health_daemon/src/glo_obs_monitor.c
- package/health_daemon/src/glo_obs_monitor.h
The same parameters are used for both glo obs and
bias monitoring so they have been merged into
a global context with access/modifier methods.
Effectively this makes the bias monitor slave
to the more 'active' obs monitor - relying on
its shorter timeout to keep current the base
station connection parameter and handle the
glonass enabled setting query/updates
swift-nav/firmware_team_planning#453
Related to:  swift-nav/piksi_v3_bug_tracking#999
> Add shared context module for glo health monitors

- package/lzo_override/lzo_override.mk
Temp fix since www.oberhumer.com/opensource/lzo/download is down.
> Override the upstream site for LZO library

- package/health_daemon/src/Makefile
- package/health_daemon/src/glo_bias_monitor.c
- package/health_daemon/src/glo_bias_monitor.h
- package/health_daemon/src/glo_health_context.c
- package/health_daemon/src/glo_health_context.h
- package/health_daemon/src/glo_obs_monitor.c
- package/health_daemon/src/glo_obs_monitor.h
The same parameters are used for both glo obs and
bias monitoring so they have been merged into
a global context with access/modifier methods.
Effectively this makes the bias monitor slave
to the more 'active' obs monitor - relying on
its shorter timeout to keep current the base
station connection parameter and handle the
glonass enabled setting query/updates
swift-nav/firmware_team_planning#453
Dev commit of swift-nav/piksi_buildroot#479
> [DEV] Add shared context module for glo health monitors

- package/piksi_leds/src/led_adp8866.c
First approach at solving swift-nav/piksi_v3_bug_tracking#997
Since the stuck leds are caused by a cache mismatch when the
piksi_leds daemon registers a successful brightness write but
the actual led brightness is incorrect. All brightness values
are updated every time the daemon updates the led states.
This may not be the actual approach we want to follow but it is available for consideration.
> Fix caching of led brightness

- package/piksi_leds/src/led_adp8866.c
Replaces cache with fully formed state structs so
the cache itself can be passed to leds_set in order
to 'flush' the values out to the driver. leds_set
has retry looping with logging on error or timeout.
Flush logic is to set flush flag if any single write
is not successful, and flush occurs before any call
to update leds when flag is set, then resets the
flag.
swift-nav/piksi_v3_bug_tracking#997
#478
> [DEV] Fix caching of led brightness

- package/libnetwork/src/libnetwork.c
Networking issues should in general be warning, not errors. Most of the other networking related problems get captured as warnings. I'm seeing errors in logs from expected behavior (server hangups) - these should be warnings. See https://github.com/swift-nav/piksi_v3_bug_tracking/issues/1023.
/cc @silverjam @benjaminaltieri
> Request errors -> warnings

- board/piksiv3/rootfs-overlay/etc/ntp.conf
- board/piksiv3/rootfs-overlay/etc/ntp.conf.gps
- board/piksiv3/rootfs-overlay/etc/ntp.conf.gpsntp
Update the mode for ntpd's NMEA refclock.
- Bit 3 indicates that the ZDA message should be used for the time, since this has complete date information.
- Bit 25 is undocumented, but configured ntpd to trust the date supplied by the receiver.  Without this ntpd assumes the receiver doesn't handle week rollover correctly, and will select the GPS epoch based on the system time (which is initially 1970).
> ntpd: Use ZDA for time, and trust GPS date.

- board/piksiv3/rootfs-overlay/etc/ntp.conf
- board/piksiv3/rootfs-overlay/etc/ntp.conf.gps
- board/piksiv3/rootfs-overlay/etc/ntp.conf.gpsntp
Master version of #491
Update the mode for ntpd's NMEA refclock.
Bit 3 indicates that the ZDA message should be used for the time,
since this has complete date information.
Bit 25 is undocumented, but configured ntpd to trust the date
supplied by the receiver.  Without this ntpd assumes the
receiver doesn't handle week rollover correctly, and will select
the GPS epoch based on the system time (which is initially 1970).
> ntpd: Use ZDA for time, and trust GPS date. [master]

- board/piksiv3/rootfs-overlay/etc/init.d/S38usb_gadget
Not a fix for anything, but useful if you're testing the usb gadget support.
From the documentation here:
https://www.kernel.org/doc/Documentation/usb/gadget_configfs.txt
> Add support for actually stopping the usb gadget

- board/piksiv3/rootfs-overlay/etc/init.d/network_poll.sh
The route status is indicated on the Link LED, but the warning message is still supressed if neither Skylark or NTRIP are enabled.
Fix for https://github.com/swift-nav/piksi_v3_bug_tracking/issues/1057
> Check for internet route regardless of Skylark/NTRIP config.

- package/libpiksi/libpiksi/include/libpiksi/util.h
- package/piksi_system_daemon/piksi_system_daemon/src/cellmodem.c
Certain things are logged one character at a time making logging output
unreadable... add a workaround for these strings.
> Workaround issues with cell modem debug logging

- package/piksi_system_daemon/piksi_system_daemon/src/ports.c
- package/zmq_adapter/src/Makefile
- package/zmq_adapter/src/zmq_adapter.c
- package/zmq_adapter/src/zmq_adapter_file.c
- package/zmq_adapter/zmq_adapter.mk
Fix for swift-nav/piksi_v3_bug_tracking#1069
Release 1.4.x version of #514 
---
At 57600 baud with a 20Hz solution frequency, Piksi produces a stream of
data that's about 5-7 KiB/s -- near the limit that the output queue can be
emptied at 57600 baud.
This causing settings reads (which are lots of small packets) to be lost
or arrive in between lots of solution messages.  The best thing we can
do here (short of implementing priority queuing and smart rate limiting)
is to issue a warning that we're getting behind, and dump the old data
that's stuck in the queue.
Note that [this change from the 1.2.x release][1] to bump the "output queue"
limit to 8192 effectively disabled the feature because the queue would never
grow beyond 4096 for a serial device (whose internal buffer is also 4096).
[1]: …
>  Dump serial output buffer when it's full [v1.4] 

- package/piksi_system_daemon/piksi_system_daemon/src/ports.c
- package/zmq_adapter/src/Makefile
- package/zmq_adapter/src/zmq_adapter.c
- package/zmq_adapter/src/zmq_adapter_file.c
- package/zmq_adapter/zmq_adapter.mk
Fix for https://github.com/swift-nav/piksi_v3_bug_tracking/issues/1069
At 57600 baud with a 20Hz solution frequency, Piksi produces a stream of
data that's about 5-7 KiB/s -- near the limit that the output queue can be
emptied at 57600 baud.
This causing settings reads (which are lots of small packets) to be lost
or arrive in between lots of solution messages.  The best thing we can
do here (short of implementing priority queuing and smart rate limiting)
is to issue a warning that we're getting behind, and dump the old data
that's stuck in the queue.
Note that [this change from the 1.2.x release][1] to bump the "output queue"
limit to 8192 effectively disabled the feature because the queue would never
grow beyond 4096 for a serial device (whose internal buffer is also 4096).
[1]: …
> Dump serial output buffer when it's full

- package/libpiksi/libpiksi/include/libpiksi/settings.h
- package/libpiksi/libpiksi/src/settings.c
- package/sbp_protocol/src/sbp_router.yml
The initial implementation of settings watchers for the health daemon was a bit copy-pasta.
This refactor covers lightly refactoring libpiksi/settings to allow settings nodes to be registered to a client that do not perform registration and only response to read responses as a way to 'watch' a particular setting.
Notes:
* Most code has merely been moved into smaller functions but the parse code has been
taken from health_daemon
* Much of this code is functionally similar to that in the settings_daemon, the next step would be
to condense that code as well
* No implementation has been performed in this PR, I will refactor health_daemon and 
others (like the simulation check in the rtcm3 bridge) as separate pull requests.
* The commits are intentionally discrete, all will be squashed if/when …
> Refactor libpiksi settings for watchers

- package/sbp_rtcm3_bridge/src/sbp.c
- package/sbp_rtcm3_bridge/src/sbp.h
- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
This incorporates #506 to remove all settings callbacks and parsing logic since that now exists in libpiksi
> Refactor rtcm3 bridge simulator watcher

- package/libnetwork/src/libnetwork.c
- package/libnetwork/src/libnetwork.h
- package/ntrip_daemon/src/ntrip_daemon.c
- package/piksi_system_daemon/piksi_system_daemon/src/ntrip.c
Based on the discussion for swift-nav/piksi_v3_bug_tracking#1079 and swift-nav/piksi_v3_bug_tracking#1032, separate username and password setting fields are not in use.
The ntrip url field may still be embedded with these values but the observed behavior is that the separate fields will override any embedded values in the url string.
> Introduce separate username and password settings for ntrip

- package/libpiksi/libpiksi/src/settings.c
- package/sbp_protocol/src/sbp_router.yml
Small behavioral fixes to the settings refactor #521 
* Allow a string value field to be "" (refactored parsing was treating this as an error)
* Route read responses from settings daemon to settings client to allow the initial update read request to complete successfully
> Allow empty string in settings write and route read resp to client

- package/piksi_system_daemon/piksi_system_daemon/src/ntrip.c
Per request: https://github.com/swift-nav/piksi_v3_bug_tracking/issues/1079#issuecomment-369485482
> Rename interval to gga_out_interval

- package/libpiksi/libpiksi/include/libpiksi/settings.h
- package/libpiksi/libpiksi/src/settings.c
- package/sample_daemon/src/sample_daemon.c
- package/sbp_protocol/src/sbp_router.yml
This is the dev PR for #506 with modifications to implement the write response changes from #397 which wasn't included in the v1.4.0-release
From the dev PR:
The initial implementation of settings watchers for the health daemon was a bit copy-pasta.
This refactor covers lightly refactoring libpiksi/settings to allow settings nodes to be registered to a client that do not perform registration and only response to read responses as a way to 'watch' a particular setting.
Notes:
* Most code has merely been moved into smaller functions but the parse code has been
taken from health_daemon
* Much of this code is functionally similar to that in the settings_daemon, the next step would be
to condense that code as well
* No implementation has been performed in this PR, I will refactor health_daemon …
> [DEV] Refactor libpiksi settings for watchers

- board/piksiv3/rootfs-overlay/etc/init.d/S38usb_gadget
Since the ethernet over USB feature was pushed until a future release, this cherry-pick removes the intermediate functionality and makes master behave the same as v1.3 release and v1.4 release.  See issues: 
https://github.com/swift-nav/piksi_v3_bug_tracking/issues/1080
and 
https://github.com/swift-nav/piksi_v3_bug_tracking/issues/691
When we pickup this feature again we should probably just revert this commit and start from there.
> Removed virtual network interfaces from USB gadget [issues 1080, 691]

- default.nix
- fetch_firmware.sh
This makes `make firmware` function as expected, some tricks need to be played with `LD_LIBRARY_PATH` so that the system Python doesn't attempt to load libraries from the "host" Python that buildroot builds.
> Add awscli to nix-shell environement for building

- Makefile
- scripts/docker.mk
Add a `docker-exec` target so that you can have multiple shells inside the same container.
> Add docker-exec target

- board/piksiv3/rootfs-overlay/etc/init.d/S81sbp_fileio_daemon_firmware
To support the NDB permission change we need to create a /persistent/ndb directory for ndb files so that firmware will be creating files in the correct location prior to restricting permissions.
> Pre-flight change for ndb permissions fix

- package/libpiksi/libpiksi/include/libpiksi/interface.h
- package/libpiksi/libpiksi/include/libpiksi/networking.h
- package/libpiksi/libpiksi/src/Makefile
- package/libpiksi/libpiksi/src/interface.c
- package/libpiksi/libpiksi/src/networking.c
- package/network_daemon/src/network_daemon.c
The ppp0 network interface does not expose TX/RX bytes via AF_PACKET as other interfaces do.
The /proc/net/dev file descriptor provides these statistics through a standard file read operation.
Busybox's version of ifconfig uses this interface to retrieve such statistics, so I've borrow the proc specific parsing code and created a new interface module to wrap the underlying behavior in case we change this implementation in the future.
Addresses DEVC-372
> Use proc to query network interface statistics

- package/libpiksi/libpiksi/include/libpiksi/interface.h
- package/libpiksi/libpiksi/include/libpiksi/networking.h
- package/libpiksi/libpiksi/src/Makefile
- package/libpiksi/libpiksi/src/interface.c
- package/libpiksi/libpiksi/src/networking.c
- package/network_daemon/src/network_daemon.c
Master version of PR #550:
> The ppp0 network interface does not expose TX/RX bytes via AF_PACKET as other interfaces do.
> 
> The /proc/net/dev file descriptor provides these statistics through a standard file read operation.
> 
> Busybox's version of ifconfig uses this interface to retrieve such statistics, so I've borrow the proc specific parsing code and created a new interface module to wrap the underlying behavior in case we change this implementation in the future.
> 
> Addresses DEVC-372
> [master:#550] Use proc to query network interface statistics

- board/piksiv3/rootfs-overlay/etc/init.d/S80zmq_router_sbp
- package/sbp_protocol/sbp_protocol.mk
- package/sbp_protocol/src/sbp_router_smoothpose.yml
I'd like to get feedback on this PR.
It adjust the zmq_router init script to use a different router yaml file in the case that smoothpose is enabled. It does this hackily, but I think that is okay since we plan to eventually do this with a better API.
It has been tested on the hardware extensively by hand (in the PR with the nav_daemon).  It requires the board to be restarted when smoothpose is disabled or enabled.
/cc @nicolekelley
> zmq_router init: use sbp_router_smoothpose.yml if Smoothpose enabled

- package/piksi_system_daemon/piksi_system_daemon/src/async-child.c
- package/sbp_fileio_daemon/src/sbp_fileio.c
- package/upgrade_tool/src/upgrade_tool.c
DEVC-336 #comment This is the master PR for #564
Summary:
- Add validation of fileio write to gate response
- Introduce differentiated failure codes in upgrade_tool
- Remove usage of exit(3) and fix status code from async child
> [master:#564] Upgrade process file io validation and error codes in upgrade_tool

- package/libnetwork/src/libnetwork.c
- package/libnetwork/src/libnetwork.h
- package/libpiksi/libpiksi/include/libpiksi/logging.h
- package/libpiksi/libpiksi/src/logging.c
- package/skylark_daemon/src/skylark_daemon.c
- package/skylark_daemon/src/skylark_settings.c
Fix for https://swift-nav.atlassian.net/browse/DEVC-381 (Slow down skylark download/upload daemon warning message rate)
Rate limit error messages coming from the skylark/ntrip daemons (over SBP) to once every 10s, all errors are still sent to syslog.
DEVC-381 #comment PR ready for review: https://github.com/swift-nav/piksi_buildroot/pull/569.
> Add rate limiting to libnetwork errors [DEVC-381]

- package/libpiksi/libpiksi/include/libpiksi/util.h
- package/libpiksi/libpiksi/src/util.c
- package/piksi_leds/src/main.c
- package/piksi_system_daemon/piksi_system_daemon/src/main.c
Moving code from `piksi_leds` into `libpiksi` to centralize the process of checking the current system for a hardware variant.
A new setting has been added in 'system_info' that reflects this API being used to determine a read only string value for the current hardware variant, called 'hardware_variant'. It will show either "DURO" or "MULTI" at this point based on the above check.
This should not be merged prior to #546 as it relies on the newly created `/cfg/duro_eeprom` resource
Addresses DEVC-38
> Create "is duro" API in libpiksi

- board/piksiv3/device_table.txt
- board/piksiv3/rootfs-overlay/etc/fstab
- package/piksi_system_daemon/piksi_system_daemon/src/main.c
- package/sbp_fileio_daemon/src/sbp_fileio.c
This addresses DEVC-336 by adding a tmpfs partition mounted as /data
Fileio daemon will inspect incoming fileio write requests and prefix the filepath with /data/ if the upgrade filepath is found ("upgrade.image_set.bin")
> [DEVC-336] Add ramdisk for update fileio and redirect current upgrades

- package/health_daemon/health_daemon.mk
- package/health_daemon/src/Makefile
- package/health_daemon/src/health_daemon.c
- package/health_daemon/src/skylark_monitor.c
- package/health_daemon/src/skylark_monitor.h
- package/libnetwork/src/libnetwork.c
- package/libnetwork/src/libnetwork.h
- package/skylark_download_daemon/src/skylark_download_daemon.c
+ Implement a simple control pipe for the skylark download daemon that allows us to get the most recent HTTP response code from the Skylark service.
+ Add a `skylark_monitor` to the `health_daemon` that looks at the POS_LLH message and checks for a "no fix" messages (that is, the message `flags` are 0).  A warning is issue every 10 seconds under the following conditions: (1) skylark is enabled; (2) there's no fix; and (3) Skylark is returning a 404 or 504 error code.
The wrinkle in this is the Skylark service tends to wait for an extended period of time before it returns a response code, so this warning check will likely take 30-40 seconds before it shows up.
+ Disconnected the device antenna and removed device from the Skylark service (then re-added) so that it simulates a device a …
>  Issue warning if skylark unhealthy and there's no fix [DEVC-369] [v1.5] 

- package/skylark_upload_daemon/src/skylark_upload_daemon.c
Accidentally made the new `--no-error-reporting` switch require an argument, fix this.
Bench testing: verified that Skylark upload daemon works again.
> Fix the --no-error-reporting switch

- board/piksiv3/rootfs-overlay/etc/init.d/usb_upgrade.sh
should fix DEVC-428 and provide more informative user output if the image is corrupt or similar.  
The crux of the issue was using $? to try and get upgrade_tool return code after piping through sbp_log, which gives you return code from sbp_log instead of upgrade_tool
The cut thing is a little hacky but I think it's better than other ways to have a lookup table of strings for return codes
> Fix usb_upgrade return code issue (DEVC-428)

- board/piksiv3/device_table.txt
- board/piksiv3/rootfs-overlay/etc/fstab
Add tmpfs located at /data to store upgrade image files without risk of running out of room
master PR for #573 
This should merge after #549 and remove any explicit creation of a /data directory
> [DEVC-336] Add ramdisk for update fileio and redirect current upgrades [master]

- package/piksi_system_daemon/piksi_system_daemon/src/cellmodem.h
- package/piksi_system_daemon/piksi_system_daemon/src/cellmodem_inotify.c
- package/piksi_system_daemon/piksi_system_daemon/src/cellmodem_probe.c
- package/piksi_system_daemon/piksi_system_daemon/src/cellmodem_probe.h
Retries added to initial modem probe attempt in `cellmodem_probe.c`
Also removed manual sbp log routine which has been superseded by `sbp_log` from `libpiksi`
> [DEVC-590] Add retry loop for initial AT command probe to candidate modem ttys

- board/piksiv3/rootfs-overlay/etc/init.d/copy_sys_logs.sh
- board/piksiv3/rootfs-overlay/etc/init.d/sdcard.sh
This ensures that data actually makes it to the disk in the event of a
power failure.  For DEVC-585 we were seeing that a new directory was not
getting created in the event of a power cycle.  A new directory was
getting created, it was just the same as the one from the previous boot
because the data was never sync'd to the device.
> Add an explicit sync call to copy_sys_logs [DEVC-585] [v1.5]

- package/cell_modem_daemon/src/cell_modem_inotify.c
- package/cell_modem_daemon/src/cell_modem_inotify.h
- package/cell_modem_daemon/src/cell_modem_probe.c
- package/cell_modem_daemon/src/cell_modem_probe.h
- package/cell_modem_daemon/src/cell_modem_settings.c
- package/cell_modem_daemon/src/cell_modem_settings.h
Squashes commits from #594 and #596, as well as removing pubsub_ctx that was
getting passed around and not being used since we have now moved to runit.
Overall summary:
A new cell_modem setting, device_override, will interject during modem
tty scans and reject candidates that do not match the override. If the
setting is changed during operation (provided cell modem is not enabled)
the currently used device will be unset and devices will be rescanned.
The refactor to remove pubsub context was merely to remove a vestigial
sbp log message routine that has been superceded by libpiksi's sbp_log
(as well as piksi_log with the SBP_LOG flag). Finally, retry logic was
added to the cell modem probe routine to allow a 'flush' on any modem
that initially emits unsolicited output.
Previous commit …
> Cell modem device override from v1.5 [DEVC-559, DEVC-590] [#594/#596:master]

- board/piksiv3/rootfs-overlay/etc/init.d/copy_sys_logs.sh
- board/piksiv3/rootfs-overlay/etc/init.d/sdcard.sh
This ensures that data actually makes it to the disk in the event of a
power failure.  For DEVC-585 we were seeing that a new directory was not
getting created in the event of a power cycle.  A new directory was
getting created, it was just the same as the one from the previous boot
because the data was never sync'd to the device.
> Add an explicit sync call to copy_sys_logs [DEVC-585] [master]

- board/piksiv3/rootfs-overlay/etc/init.d/S75dev_boot
- board/piksiv3/rootfs-overlay/etc/init.d/copy_from.sh
- board/piksiv3/rootfs-overlay/usr/bin/chat_command
- board/piksiv3/rootfs-overlay/usr/bin/kill_chat_command
- package/piksi_system_daemon/piksi_system_daemon/src/async-child.c
- package/piksi_system_daemon/piksi_system_daemon/src/cellmodem.c
Do work to make sure pppd and chat are fully terminated
+  Add a wrapper for the chatscript that records the process id, so we can
request that it stop when the cell modem is disabled.
+  Make sure pppd is fully terminated by sending it SIGINT, SIGTERM, then
SIGKILL.
Fix crash when dumping pppd output
+  Remove hack that tried to fix-up strings that pppd/chat would write one
character at a time... just in case this was contributing to the crash.
+  Also, guard against a null buffer pointer and make sure that we call
strlen on something that's guaranteed to be null temrinated.
+  The current working theory is that when the pppd daemon would
occasionally start outputing "garbage" from the ppp stream, this would
overflow the SBP max payload and strlen would not terminate the
buffer... thus …
> Add more sophisticated facilities for terminating pppd/chat, fix crashes in capturing output [DEVC-560]

- package/piksi_system_daemon/src/main.c
This PR Makes sure we know what buildroot we are testing via version strings in master:
should close this request from last year:
https://github.com/swift-nav/firmware_team_planning/issues/331
/cc @axlan 
I tested on PROD, and Dev.  Works as expected.
In dev mode, the uimage version will be used.
A new setting is created in dev mode to tell you what imageset version is in use for dev bootloader.
> Update read-only version/date settings in piksi_system_daemon for DEV

- package/piksi_system_daemon/piksi_system_daemon/src/cellmodem.c
- package/piksi_system_daemon/piksi_system_daemon/src/cellmodem.h
- package/piksi_system_daemon/piksi_system_daemon/src/cellmodem_inotify.c
> [DEVC-675] Add probe retries timer callback for device override during boot period

- default.nix
When I set up my system with NixOS 18.03 I had to add this to default.nix in order to get it to build.
> Add binutils to default.nix

- package/libnetwork/src/libnetwork.c
GGA sentence upload support leaked a file descriptor, causing uploads to fail when 1k descriptors where allocated/leaked.  Fix this and add support for uploading the last cached GGA sentence if we fail to read from the file where the GGA sentence is stored.
Ran overnight with ntrip enabled on an endpoint that requires GGA.
>  Fix for continuous GGA upload [DEVC-708] [v1.5] 

- board/piksiv3/rootfs-overlay/etc/init.d/S75dev_boot
- board/piksiv3/rootfs-overlay/etc/init.d/copy_from.sh
Pass SERVER_IP and SD_PATH, sync copy_from.sh with v1.5: these are passed so that an init_script.sh can pull things from tftp if it desires.
> Allow init_script.sh to pull down things from TFTP

- package/gnss_convertors/gnss_convertors.mk
- package/librtcm/librtcm.mk
- package/nmea_daemon/src/Makefile
- package/sbp_rtcm3_bridge/src/Makefile
Update pointers to `librtcm` (https://github.com/swift-nav/librtcm/pull/36) and `gnss-converters` (https://github.com/swift-nav/gnss-converters/pull/73) for RTCM MSM support.
This implements support of MSM4-7 messages for all constellations defined in RTCM 10403.3
Note that MSM4/6 does not currently support GLO. There's a follow-up issue https://swift-nav.atlassian.net/browse/EX-155 for that.
Tested with live rooftop signal against the only MSM station in range ORIV00FIN0, with baseline of 26km, and sending MSM7 messages for all constellations (>100 obs in total). Produces fix and has been running a couple of nights without incidents.
Tested against other EUREF NTRIP casters producing legacy obs, and MSM4 / MSM5 obs, and verified that base observations arrive to console and look …
> EX-156: RTCM MSM support

- package/piksi_leds/src/firmware_state.c
- package/piksi_leds/src/firmware_state.h
- package/piksi_leds/src/manage_led.c
Refactoring the code in piksi_leds (manage_led.c and firmware_state.c) to account for INS mode flags in position messages, as well as define the specific led states to track separately for each led (pos, link, mode) based on the [FR for duro](https://docs.google.com/document/d/1yIaBHhSVWWIIZnVPjWSPCmRbOs-xxixhyTqH9373s9w/edit#)
> Duro inertial led behavior

- .travis.yml
- scripts/check_for_s3_cred.sh
This alerts the user when they kick off a build from a fork which would prevent the results from being uploaded
> check aws creds

- scripts/docker.mk
Without this change I was getting an error running 'make docker-setup' due to a upper case character in my username. This seems to fix it but not sure this is the 'correct' way to fix it.
> Make repo name lower case for OSX

- package/libnetwork/src/libnetwork.c
- package/libnetwork/src/libnetwork.h
- package/nmea_daemon/src/nmea_daemon.c
- package/ntrip_daemon/src/ntrip_daemon.c
- package/piksi_system_daemon/piksi_system_daemon/src/ntrip.c
Changes:
- Format GGA upload string according to the NTRIP 2.0 spec
- Add an option (defaulting to false) that allows the user to enable NTRIP 1.0 style GGA upload
- Rate limit the "connection stalled" message so that the user isn't spammed when the device is starting up
- Strip the "Expect" header from the what cURL sends by default when doing an upload so that cURL won't expect the server to do the "expect/continue" behavior (which is intended as a way to ask the server if an upload is ok).
- Fix a logic inversion bug in the handling of the cache for `fill_with_gga_xfer_cache`, previously we would error out if there was a cache
Bench testing:
- Bench test overnight connected to a SNIP NTRIP caster without error
> NTRIP GGA improvements [DEVC-708] [v1.5]

- package/gnss_convertors/gnss_convertors.mk
- package/librtcm/librtcm.mk
- package/libsbp/libsbp.mk
- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Add callbacks for GLO FCN map and update librtcm & gnss-converters pointers to pull in https://github.com/swift-nav/gnss-converters/pull/83 and https://github.com/swift-nav/librtcm/pull/42.
Note that `libsbp` version must match with FW so that correct GLO ephemeris messages are picked up.
Tested on the bench
- against live MSM7 stream from ORIV00FIN0 converted into MSM4 stream with RTKLIB `str2str`
- against zero-baseline Novatel OEM6 native stream converted into MSM5 stream with RTKLIB `str2str`
Fixes nicely in all cases with the dev FW+LNSP PRs that map L2 observations into usable ones (https://github.com/swift-nav/piksi_firmware_private/pull/2057)
(I got only float solution on the zero-baseline Novatel setup with current master FW, although the result is same when converting the stream …
> EX-155: MSM4/6 GLO support

- package/ntrip_daemon/overlay/etc/init.d/S82ntrip_daemon
- package/skylark_daemon/overlay/etc/init.d/S82skylark_daemon
Behavior that cropped up in #639, not sure why this wasn't happening on master previously.
> Adding touch to control/socket so settings loop init doesn't fail

- board/piksiv3/rootfs-overlay/etc/init.d/S38usb_gadget
- package/ports_daemon/overlay/etc/init.d/S82ports_daemon
- package/ports_daemon/ports_daemon/src/ports.c
- package/ports_daemon/ports_daemon/src/serial.c
This simply duplicates all related code for ttyGS0/usb0, s/0/2g, and bypasses the settings registration so that this port cannot be altered and is always available.
> [DEVC-694] Add 2nd virtual com for SBP

- package/upgrade_tool/upgrade_tool.mk
The current `upgrade_tool` can't upgrade if a NAP version > 4.x is loaded, fix this by bringing in these changes:
- https://github.com/swift-nav/piksi_upgrade_tool/commit/07c40c75a2227530dc086471de3672775f4d6cc2
https://github.com/swift-nav/piksi_inertial_ipsec_crl/compare/3a051339ecf391f4f8e5193bccccedb2ea93a050...469beacd95c1bb0782e2741bb376eb6744f07da5
> Fix upgrade_tool compatibility with NAP >= 4.x

- package/nmea_daemon/src/nmea_daemon.c
Change the contract for /var/run/nmea/GGA so that it's never expected to
be empty if we can access it.  This makes the error logging here not
result in an error when the device starts up and has not yet gotten a
fix yet.
See https://swift-nav.atlassian.net/browse/DEVC-764
> Make sure /var/run/nmea/GGA is never empty [DEVC-764]

- package/ports_daemon/ports_daemon/src/serial.c
Add 460800bps and 921600 bps to the list of available baud rates for the device to device use case.
> Update the baudrate list for UARTs

- package/health_daemon/src/Makefile
- package/health_daemon/src/health_daemon.c
- package/health_daemon/src/ntrip_obs_monitor.c
- package/health_daemon/src/ntrip_obs_monitor.h
Adds a timer that checks for base obs gated on ntrip enabled.
Also fixes a bug from the zmq refactor where the pubsub context wasn't getting attached properly to the loop context.
> [DEVC-426] Add warning if no base obs seen when ntrip is enabled

- package/gnss_convertors/gnss_convertors.mk
- package/librtcm/librtcm.mk
Pull in changes from swift-nav/librtcm#45, swift-nav/librtcm#46, and swift-nav/gnss-converters#87 to address [DEVC-767](https://swift-nav.atlassian.net/browse/DEVC-767)
> Update librtcm and gnss-converters to support L1P/L2P warnings

- package/gnss_convertors/gnss_convertors.mk
- package/librtcm/librtcm.mk
> [DEVC-767] Update librtcm and gnss-converters to support L1P/L2P warnings [v1.6]

- board/piksiv3/rootfs-overlay/etc/init.d/S09sysctl
- board/piksiv3/rootfs-overlay/etc/init.d/template_runsv.inc.sh
- board/piksiv3/rootfs-overlay/etc/network/interfaces
- package/common_init/overlay/etc/ifplugd/ifplugd.action
- package/common_init/overlay/etc/init.d/S83ifplugd
- package/common_init/overlay/etc/init.d/ifplugd.sh
- package/common_init/overlay/etc/sudoers.d/ifplugd
- package/libnetwork/docs/about.md
- package/piksi_system_daemon/overlay/etc/init.d/update_eth0_config
+ There's a behavior change in dhcpcd that seems to cause it to grab
eth0 regardless of what's in `/etc/network/interfaces`-- fix this by
configuring `/etc/dhcpcd.conf` to ignore eth0 initially.
+ Give `template_runsv.sh` better quoting of arguments so it'll be more
likely to pass through a linter.
+ Make `template_runsv.sv` no try to remove the service directory after
it's been generated (which causes runsv to spit out errors).
+ Remove some of the setcap stuff from the ifplugd.sh script which isn't
needed since ifplugd is run with sudo now
+ Make ifplugd run less often with -a, -q, and -p
> Prevent dhcpcd from grabbing eth0 [DEVC-802]

- board/piksiv3/rootfs-overlay/etc/init.d/S09sysctl
- board/piksiv3/rootfs-overlay/etc/init.d/template_runsv.inc.sh
- board/piksiv3/rootfs-overlay/etc/network/interfaces
- package/common_init/overlay/etc/ifplugd/ifplugd.action
- package/common_init/overlay/etc/init.d/S83ifplugd
- package/common_init/overlay/etc/init.d/ifplugd.sh
- package/common_init/overlay/etc/sudoers.d/ifplugd
- package/libnetwork/docs/about.md
- package/piksi_system_daemon/overlay/etc/init.d/update_eth0_config
+ There's a behavior change in dhcpcd that seems to cause it to grab
eth0 regardless of what's in `/etc/network/interfaces`-- fix this by
configuring `/etc/dhcpcd.conf` to ignore eth0 initially.
+ Give `template_runsv.sh` better quoting of arguments so it'll be more
likely to pass through a linter.
+ Make `template_runsv.sv` no try to remove the service directory after
it's been generated (which causes runsv to spit out errors).
+ Remove some of the setcap stuff from the ifplugd.sh script which isn't
needed since ifplugd is run with sudo now
+ Make ifplugd run less often with -a, -q, and -p
Related issues: DEVC-836, DEVC-780, DEVC-806, DEVC-733, DEVC-801, DEVC-784
> Prevent dhcpcd from grabbing eth0 [DEVC-802] [v1.6]

- board/piksiv3/patches/linux/0004-mtd-spi-nor-macronix-ear-read-write-support.patch
Patch to the mtd/spi-nor driver needed to get Macronix MX25L51245G sample board to boot with a production image as well as use the upgrade_tool without issues.
Reference findings:
https://swift-nav.atlassian.net/wiki/spaces/~42118676/pages/234717346/Macronix+Flash+Bring+Up+Findings
> [DEVC-570] mtd driver to support macronix flash

- fetch_firmware.sh
- fetch_firmware.sh.m4
Test strategy:
1. with aws credentials (succeeds as expected): 
m4 -DM4_BUCKET=swiftnav-artifacts -DM4_FW_VERSION=v1.5.0-develop-2018062919 -DM4_NAP_VERSION=v1.5.0-develop-2018062919 fetch_firmware.sh.m4 > fetch_firmware.sh
./fetch_firmware.sh
2. without aws credentials (fails as expected):
m4 -DM4_BUCKET=swiftnav-artifacts -DM4_FW_VERSION=v1.5.0-develop-2018062919 -DM4_NAP_VERSION=v1.5.0-develop-2018062919 fetch_firmware.sh.m4 > fetch_firmware.sh
./fetch_firmware.sh
3. with aws credentials (succeeds as expected):
m4 -DM4_BUCKET=swiftnav-artifacts -DM4_FW_VERSION=v1.6.3 -DM4_NAP_VERSION=v1.6.3 fetch_firmware.sh.m4 > fetch_firmware.sh
./fetch_firmware.sh
4. without aws credentials (fails as expected):
m4 -DM4_BUCKET=swiftnav-artifacts -DM4_FW_VERSION=v1.6.3 -DM4_NAP_VERSION=v1.6.3 …
> DEVC-732: Integrate sdk fpga into image generation

- fetch_firmware.sh
- fetch_firmware.sh.m4
If M4_BUCKET == swiftnav-releases
no aws credentials required, fetch the piksi_sdk_fpga.bit
If M4_BUCKET == swiftnav-artifacts
aws credentials required, fetch the piksi_prod_fpga.bit
While here, simplify by dropping microzed (and HW_CONFIG)
> DEVC-732: Integrate sdk fpga into image generation (for v1.6.x)

- package/ports_daemon/ports_daemon/src/whitelists.c
Does not seem to be populated, removing it from the whitelist
> Removed `MSG_UART_STATE`

- package/sbp_protocol/src/sbp_router_smoothpose.yml
~/s/p/p/s/src ❯❯❯ diff sbp_router.yml sbp_router_smoothpose.yml
diff --git a/sbp_router.yml b/sbp_router_smoothpose.yml
index d426f850..e6250097 100644
--- a/sbp_router.yml
+++ b/sbp_router_smoothpose.yml
@@ -1,3 +1,10 @@
+# This file is a variant the stock sbp_router.yml With it, the router sends the
+# "best position" and "best velocity" estimates through a new nav_daemon port
+# before going to the external interfaces.  It can be used to allow a process
+# like a loosely coupled INS filter to intercept and transform the best GNSS
+# position and velocity estimates they go on the wire The key changes to the
+# stock config are highlihged with the string **Smoothpose Change**
+
name: SBP_ROUTER
ports:
- name: SBP_PORT_FIRMWARE
@@ -21,6 +28,14 @@ ports:
- { action: REJECT, prefix: [0x55, …
> Fixup typo in sbp_router_smoothpose.yml

- package/gnss_convertors/gnss_convertors.mk
- package/librtcm/librtcm.mk
Release version of https://github.com/swift-nav/piksi_buildroot/pull/705
Pulls in swift-nav/gnss-converters#91 to fix week roll-over issues
> [v16] EX-230: Update gnss-convertors time diff handling

- package/gnss_convertors/gnss_convertors.mk
- package/librtcm/librtcm.mk
- package/rtcm3_protocol/src/framer_rtcm3.c
- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Pull in https://github.com/swift-nav/gnss-converters/pull/95 and https://github.com/swift-nav/librtcm/pull/49 that should fix missing observations at TOW=0.
Additionally log CRC errors in RTCM framer to get some visibility of possible problems there.
> EX-245: update gnss_convertors and librtcm for week rollover fixes

- package/gnss_convertors/gnss_convertors.mk
- package/librtcm/librtcm.mk
- package/rtcm3_protocol/src/framer_rtcm3.c
- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Release version of https://github.com/swift-nav/piksi_buildroot/pull/721
> [v16] EX-245: update gnss_convertors and librtcm for week rollover fixes

- package/libnetwork/src/libnetwork.c
Don't set the HTTP header in the init functions - set them after.
I noticed there are some instances where the chunk can get updated outside of the init function - not sure how this ends up picking the added headers. Move the setting of the header to outside of the init.
/cc @silverjam @benjaminaltieri
> Set the HTTP header after the init function

- board/piksiv3/rootfs-overlay/etc/init.d/S98rtc_load
Manually loading the rtc module doesn't seem to actually set the system
time using the value stored in the RTC.  Correct this by manually
calling the hwclock utility to set the Linux system time from the RTC.
> Manually set the system time from the RTC [DEVC-1000]

- package/common_init/overlay/etc/init.d/S98rtc_load
Manually loading the rtc module doesn't seem to actually set the system
time using the value stored in the RTC.  Correct this by manually
calling the hwclock utility to set the Linux system time from the RTC.
> Manually set the system time from the RTC [DEVC-1000] [master]

- board/piksiv3/rootfs-overlay/etc/init.d/S85piksi_firmware
Minimal bench testing here, but I have added logging facility to allow these activities to be caught in `syslog` while increasing the timeout on waiting for uarts to come up.
> Increase piksi_firmware init UART timeout past watchdog

- scripts/docker.mk
This is set inside of the buildroot config, so there's no reason to set
it in the environment.
> Remove BR2_CCACHE_DIR for docker.mk

- package/endpoint_adapter/src/endpoint_adapter.c
- package/ntrip_daemon/src/ntrip_settings.c
* update enpoint_adapter.c to check of --name is set, return -1 otherwise
* update ntrip_daemonm.c to add the --name argument when invoke enpoint_adapter.
> Updated command line argument in  endpoint adapter [DEVC-1052]

- package/skylark_daemon/src/skylark_settings.c
This reverts commit 97b8bad284487d222ffc337313aee443cbd9475a which brought in the klobuchar change slated for master only, so we're taking it out of v2.1
> Revert "Move skylark.enable registration to PFWP and add watch trigger (#790)"

- package/gnss_convertors/gnss_convertors.mk
- package/librtcm/librtcm.mk
- package/sbp_nmea_bridge/src/sbp_nmea_bridge.c
- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Pull in https://github.com/swift-nav/gnss-converters/pull/123
Fixes the issue https://swift-nav.atlassian.net/projects/EX/issues/EX-345 on bench.
The buildroot PR does better than 2.1 on HITL msm4 scenario: https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-msm4&build_type=release&firmware_versions=v2.1.1-5-g89aaee46,v2.1.1&groupby_key=firmware&display_type=table
(one run failed RTK because of no base observations)
> EX-345 Suppress unsupported codes in gnss-converters [v2.1]

- package/piksi_ins/piksi_ins.mk
2.1.4 pointer did not have updated libnanomsg and is not working - need 2.1.5 fix from CRL
> revert Smoothpose pointer to 2.1.3

- README.md
- default.nix
- scripts/run-clang-format
Trying to get a handle on the version of clang-format being used. Nixpkgs tells me 5.0.1 but I've heard reports that 6.0 is what works on Ubuntu.
According to the [this](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/clang-tools/default.nix), `clang-tools` should pull its version from the `clang` version but that does seem to be working so I have removed the 3.8 specifier in `default.nix`.
Also adding a blurb around the new automated formatting checks in readme in hopes of capturing the correct process for obtaining the version you need in the readme. Open to comments on a more appropriate place to put that.
> Fix versioning of clang-format for automated format checks [DEVC-1106]

- package/common_init/overlay/etc/init.d/reset2defaults.sh
For DEVC-1102, remove config.ini only, instead of all the files and sub folders in the persistent directory.
> The magic USB file to clear settings wipes license and calibration files [DEVC-1102]

- package/gnss_convertors/gnss_convertors.mk
Pull in https://github.com/swift-nav/gnss-converters/pull/132
No more duplicate OBS errors in HITL:
https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-msm7&build_type=master&firmware_versions=v2.0.0-develop-2018092118-10-g04de7b44&groupby_key=firmware&display_type=table
Couple of runs did not have any base observations, but that's in line with current master.
> EX-347: Fix duplicate GLO MSM obs on first fix [master]

- package/gnss_convertors/gnss_convertors.mk
Release version of https://github.com/swift-nav/piksi_buildroot/pull/873
https://gnss-analysis.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend-post,live-roof-650-townsend-msm7,live-roof-650-townsend-ntrip-bard-jrsc,live-roof-650-townsend-msm4&build_type=buildroot_pr&firmware_versions=v2.1.6-2-ga1d2c555&groupby_key=scenario_name&display_type=table
> EX-347: Fix duplicate GLO MSM obs on first fix [release]

- board/piksiv3/patches/grpc_custom/0002-fixup-nixos-compile.patch
- default.nix
- package/orion_daemon/orion_daemon.mk
- package/orion_daemon/src/Makefile
- package/protobuf_custom/protobuf_custom.mk
- scripts/wrappers/bin/aws
- scripts/wrappers/bin/c++
Add various fix-ups so master can build with NixOS:
+ The protobuf package's libtool script wouldn't search the correct dir to find the libatomic.so from the cross compiler, instead it was picking it up from the host
+ gRPC need some fix-ups to the generation of install commands for headers, otherwise this would fail because the command line generated was too large for `/bin/sh`
+ We forced buildroot to use g++ as the host c++ compiler (within gRPC) to avoid issues with clang++
+ Orion daemon needed to pick up flags from buildroot (apparently needed to pick-up the flto flag in order to link correctly, not sure on this, but the .mk change brings orion_daemon in-line with other packages)
> NixOS build broken on master [DEVC-1122]

- package/ports_daemon/ports_daemon/src/whitelists.c
For Duro inertial, I think it is a good idea to remove raw IMU data from the UART1 default whitelist.  100Hz raw IMU data will start to eat a bit of the port per HITL graphs: (edited)
It’s about 2kB/sec
Pasted image at 2018-09-14, 2:46 PM 
16,000 bits per second / 115200 is about 14% of overall bandwidth
I decided to leave AUX msg and Magnetometer messages since they are lower bandwidth.
requires corresponding piksi_tools PRs below to document as well
> Remove IMU_RAW from UART1 default whitelist

- package/piksi_system_daemon/overlay/etc/sudoers.d/piksi_system_daemon
- package/piksi_system_daemon/src/main.c
Correct spawn_nc for rename of fio_ex -> fileio [DEVC-1121].
> Fix piksi_multitool upgrade path for removal of fio_ex user [DEVC-1121] [release]

- package/piksi_system_daemon/overlay/etc/sudoers.d/piksi_system_daemon
- package/piksi_system_daemon/src/main.c
Correct spawn_nc for rename of fio_ex -> fileio.
> Fix piksi_multitool upgrade path for removal of fio_ex user [DEVC-1121]

- package/standalone_file_logger/standalone_file_logger/src/standalone_file_logger.cc
Clarify that this is not important to the user.
> Downgrading standalone logger daemon startup message [DEVC-1165]

- package/gnss_convertors/gnss_convertors.mk
- package/librtcm/librtcm.mk
- package/libsbp/libsbp.mk
- package/sample_daemon/src/udp_socket.c
- package/sample_daemon/src/udp_socket.h
- package/sbp_protocol/src/framer_sbp.c
Move also gnss-convertors and librtcm pointers to master version.
Feel free to merge once all is green, these have already been through bench and HITL tests in https://github.com/swift-nav/piksi_buildroot/pull/886, https://github.com/swift-nav/piksi_buildroot/pull/883, and https://github.com/swift-nav/piksi_buildroot/pull/879
> Update libsbp to 2.4.1

- package/orion_daemon/src/orion.proto
- package/orion_daemon/src/orion_daemon.cc
Orion needs to see positions at most every second. Send only positions out when the previous recorded tow is different, hopefully the start of a new 1s tow. Also, don't send up invalid positions.
> Add some checks to keep from sending out bad frames to orion.

- package/sbp_fileio_daemon/sbp_fileio_daemon/src/sbp_fileio.c
Attempting to list a directory that does not exist results in a
readdir(NULL) call. This causes a core dump.
We now ignore any requests on non-existing directories
> Fix core dump on fileio [DEVC-1138]

- package/gnss_convertors/gnss_convertors.mk
- package/sbp_nmea_bridge/src/sbp_nmea_bridge.c
- package/sbp_protocol/src/sbp_router.yml
- package/sbp_protocol/src/sbp_router_smoothpose.yml
The SBP baseline heading message was not being routed and supported in the nmea convertor correctly.
> Fix for nmea hdt message not being sent [MAP-691]

- package/gnss_convertors/gnss_convertors.mk
- package/librtcm/librtcm.mk
- package/libswiftnav/libswiftnav.mk
- package/sbp_nmea_bridge/src/sbp_nmea_bridge.c
- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Pulls in https://github.com/swift-nav/librtcm/pull/66 and https://github.com/swift-nav/gnss-converters/pull/143 to add support for MSM messages in addition to legacy 1004/1012.
Add configuration options for selecting RTCM out mode, defaulting to MSM5.
Some tens of hours of running on bench in zero-baseline configuration, one Piksi sending RTCM and the other receiving, with 1Hz and 5Hz observation rates without glitch. Tested both over UART and TCP. When setting obs rate to 10Hz, the device's LEDs look like it's working but the console chokes so no way of verifying the output.
Tested switching RTCM output type between the different choices while connection is open, works without a glitch. (note the 60s delay though when switching from legacy obs back to MSM)
Worked nicely, RTK baseline …
> EX-388: RTCM output mode selection and MSM out

- package/nmea_protocol/src/info_nmea.c
Revert the whitespace change from DEVC-1232 which might explain broken NMEA output
> DEVC-1232 Fix info_nmea

- .dockerignore
- .gitignore
- Makefile
- scripts/check-docker-sync
- scripts/docker.mk
- scripts/docker_entrypoint.sh
- scripts/gen-docker-sync
- scripts/make_help.txt
- scripts/run-aws-google-auth
- scripts/run-docker-wipe
+ Use the docker-sync tool to sync everything in `/piksi_buildroot` into a container volume-- the primary use-case of this is to support building on a remote `$DOCKER_HOST`.
+ Add the new targets: `docker-sync-setup`, `docker-sync-start`, `docker-sync-stop`, `docker-sync-logs`, and `docker-sync-cleanup`
+ Add `docker-aws-google-auth` to facilitate getting fresh AWS credentials
> Add support for syncing into a docker container

- .vimrc
- scripts/gen-clang-complete
- scripts/gen-docker-sync
+ Add docs for the project specific .vimrc
+ Remove -std=gnu11 from clang-complete since it doesn't work for c++
code (and gnu11 should be the default for C code in clang-tidy).
+ Make docker-sync config generation error out if DOCKER_HOST isn't set
> Docs, fixup clang-complete, and docker-sync [DEVC-1087]

- package/libpiksi/libpiksi/src/logging.c
- package/libpiksi/libpiksi/src/sbp_rx.c
- package/libpiksi/libpiksi/src/sbp_tx.c
- package/libpiksi/libpiksi/src/util.c
- package/sbp_cli/src/sbp_log.c
- package/starling_daemon/overlay/etc/endpoint_router/sbp_router_starling.yml
This replaces the previous behavior of using `popen` with the `sbp_log` application for every log.
> Grab the firmware implementation of logging over SBP.

- package/cell_modem_daemon/src/cell_modem_settings.c
- package/libpiksi/libpiksi/include/libpiksi/settings.h
- package/libpiksi/libpiksi/src/settings.c
- package/metrics_daemon/metrics_daemon/src/metrics_daemon.c
- package/ntrip_daemon/src/ntrip_settings.c
- package/orion_daemon/src/orion_daemon.cc
- package/ota_daemon/src/ota_settings.c
- package/piksi_system_daemon/src/main.c
- package/ports_daemon/ports_daemon/src/ports.c
- package/ports_daemon/ports_daemon/src/serial.c
- package/ports_daemon/ports_daemon/src/whitelists.c
- package/sample_daemon/src/sample_daemon.c
- package/sbp_nmea_bridge/src/sbp_nmea_bridge.c
- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
- package/sbp_settings_daemon/sbp_settings_daemon/src/settings.c
- package/sbp_settings_daemon/sbp_settings_daemon/test/run_sbp_settings_daemon_test.cc
- package/skylark_daemon/src/skylark_settings.c
- package/standalone_file_logger/standalone_file_logger/src/standalone_file_logger.cc
This feature lets the Piksi return more detailed error codes to describe why a setting failed to update.
An enum defining the various codes will be moved into libpiksi.h, exposing the values for every package.
The errors defined will be:
Setting Does Not Exist
Setting Did Not Parse
Setting Value Invalid
Setting is read-only
Setting is not currently modifiable
One callback in ntrip_daemon has been modified to use these new codes.
Ideally, all settings callbacks everywhere would be updated.
settings_daemon/settings.c: /s/settings_update/setting_update to resolve
a name conflict with libpiksi/setting.h
See also:
https://github.com/swift-nav/piksi_tools/pull/914
> Add additional settings update error codes [DEVC-1225] [DEVC-1219]

- package/sbp_nmea_bridge/src/sbp_nmea_bridge.c
The sender id in NMEA GGA messages currently switches between 0 and the correct value (see https://swift-nav.atlassian.net/projects/EX/issues/EX-408). 
Fixed by not overwriting sender ID with zero (apparently we get also the forwarded base station observations here).
master 20181031 outputs sender ID only occasionally:
```
$GPVTG,,T,,M,0.01,N,0.02,K,D*25
$GPGGA,090056.40,6126.8177524,N,02351.5087202,E,4,22,0.6,184.07,M,0.0,M,2.4,0000*45
$GPVTG,,T,,M,0.00,N,0.01,K,D*27
$GPGGA,090056.60,6126.8177512,N,02351.5087208,E,4,22,0.6,184.07,M,0.0,M,0.6,0000*48
$GPVTG,,T,,M,0.01,N,0.02,K,D*25
$GPGGA,090056.80,6126.8177506,N,02351.5087214,E,4,22,0.6,184.07,M,0.0,M,0.8,0000*40
$GPVTG,,T,,M,0.01,N,0.01,K,D*26
$GPGGA,090057.00,6126.8177512,N,02351.5087220,E,4,22,0.6,184.07,M,0.0,M,1.0,0057*40 …
```
> EX-408: Only update non-zero sender id

- README.md
Snuck in a command instruction showing the new docker support for `clang-format` too. Can't wait for `clang-tidy` to make it's way in there 😄
> Update readme to reflect current limitations in building from source [DEVC-1186][master]

- package/health_daemon/src/skylark_monitor.c
- package/libpiksi/libpiksi/src/util.c
Seeing the following from health daemon:
```
Nov 2 04:09:11 piksi local0.err health_daemon[2198]: error opening /var/run/skylark/enabled
Nov 2 04:09:21 piksi local0.err health_daemon[2198]: error opening /var/run/skylark/enabled
Nov 2 04:09:31 piksi local0.err health_daemon[2198]: error opening /var/run/skylark/enabled
Nov 2 04:09:41 piksi local0.err health_daemon[2198]: error opening /var/run/skylark/enabled
Nov 2 04:09:51 piksi local0.err health_daemon[2198]: error opening /var/run/skylark/enabled
root@piksi:~ # lsof|grep health_daemon|grep skylark/enabled|wc -l
1010
```
> Fix handle leak in health_daemon [DEVC-1260]

- package/resource_monitor/resource_monitor/src/query_sockets.c
- package/resource_monitor/resource_monitor/src/query_sys_state.c
- package/resource_monitor/resource_monitor/src/resource_query.c
+ Unix socket seqpackets follow the same line format as all other unix sockets, so parse accordingly
+ Move the `extrace.log` so that it doesn't get picked up as a system log in `/var/log`-- the output file is cycled every N seconds (according to the interval for the resource monitor) so we shouldn't have issues with it filling up the drive (unless the resource monitor interval is set to be huge).
+ Squelch some misc. debugging output
> Handle unix seqpacket sockets, clean-up more output [DEVC-1254]

- board/piksiv3/device_table.txt
- package/common_init/overlay/etc/fstab
As of #941 upgrade tool isn’t able to unpack encrypted downloads.
Reverting removal of `/upgrade_data` and upping the tmpfs sizes to accommodate downloads of >15Mb
> Revert removal of upgrade_data folder [DEVC-1263]

- package/upgrade_tool/upgrade_tool.mk
Bringing in the following changes: https://github.com/swift-nav/piksi_upgrade_tool/compare/v2.2.4...v2.2.6
> Update upgrade_tool to v2.2.6

- package/gnss_convertors/gnss_convertors.mk
Pull in https://github.com/swift-nav/gnss-converters/pull/154/ (lower MSM timeout from 60 s to 5 s, so when switching to legacy stream the observations come back faster).
> EX-415: MSM 5s timeout

- package/common_init/overlay/etc/init.d/gps_adapter.sh
- package/endpoint_adapter/src/endpoint_adapter.c
- package/endpoint_router/endpoint_router/src/endpoint_router.c
- package/libpiksi/libpiksi/include/libpiksi/endpoint.h
- package/libpiksi/libpiksi/src/endpoint.c
So that the `endpoint_adapter` that feeds ntpd can connect to the `endpoint_router` once it starts add a naive retry that retries during the initial connection phase.
> Add retry support to endpoint_adapter and endpoints [DEVC-1271]

- .gitmodules
- Jenkinsfile
- Makefile
- docker-compose.yml
- package/sbp_fileio_daemon/sbp_fileio_daemon.mk
- scripts/Dockerfile.jenkins
- scripts/docker-compose.yml
- scripts/env-setup.mk
This runs a build pipeline for piksi_buildroot.
Limitations:
- Only runs on PRs and branch pushes (not for tags)
- Pushes artifacts to a separate S3 bucket as not to conflict with the Travis-run builds
- No notifications sent (other than posting status to the PRs as can be seen in this PR)
- Doesn't use any kind of persistent ccache yet
The limitations will be addressed in a separate PR - but this one should allow us to evaluate if it works ok in parallel to travis builds.
> Jenkins build pipeline

- package/gnss_convertors/gnss_convertors.mk
- package/librtcm/librtcm.mk
- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Issue https://swift-nav.atlassian.net/browse/EX-445
Pull in https://github.com/swift-nav/gnss-converters/pull/159 that implements sending of 1006, 1008, and 1033.
Add settings `rtcm_out.antenna_height`, `rtcm_out.ant_descriptor` and `rtcm_out.rcv_descriptor`, and fill the descriptors with default values.
- antenna height is output in 1006 and respond to changing the value from console
- antenna type is output as `HXCGPS500       NONE` in 1008 & 1033 and responds to changes
- receiver type output as `PIKSI` in 1033 and responds to changes
- station_id is the same in all messages
```
$ nc 192.168.1.13 55556 | gpsdecode | grep "type\":1006"
{"class":"RTCM3","device":"stdin","type":1006,"length":21,"station_id":669,"system":["GPS","GLONASS","GALILEO"],"refstation":false,"sro":true,"x":2795371. …
```
> EX-445: Send receiver&antenna descriptors via RTCM out

- package/metrics_daemon/metrics_daemon/src/metrics_daemon.c
Added a check on string length when searching the json tree to prevent using wrong nodes which start with the same sub-string as parent when looping through the folders.
> fix metrics mismatch issue as described in [ESD-899]

- package/health_daemon/src/baseline_monitor.c
(v2.2 version of #1019)
* reduce baseline alert to once every 10 seconds
* clang format
> reduce baseline alert to once every 10 seconds [v2.2]

- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Base observations were also being erroneously sent over RTCM. (issue https://swift-nav.atlassian.net/projects/EX/issues/EX-456)
> EX-456: Don't relay base observations over RTCM

- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Release version of https://github.com/swift-nav/piksi_buildroot/pull/1017
> EX-456: Don't relay base observations over RTCM [release]

- Makefile
- scripts/gen-docker-sync
This affects DOCKER_HOST var for docker, using <host-ip>:<port> as a
value in the DOCKER_HOST variable used to work, but no longer in the
latest version of Docker for Mac.
See https://github.com/golang/go/issues/19297
> Golang 1.9 decided that <host>:<port> isn't a URL anymore

- package/ports_daemon/ports_daemon/src/whitelists.c
A temporary solution to ESD-922. Changing a setting on one piksi would
also send a WRITE_RESP to a second piksi, also causing an unintentional
setting change there.
Backport of (#1029)
> remove WRITE_RESP message from udp/tcp_client [ESD-922]

- package/gnss_convertors/gnss_convertors.mk
- package/librtcm/librtcm.mk
- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Check `rtcm_out.antenna_height` setting for both minimum and maximum value. 
Pulls in https://github.com/swift-nav/librtcm/pull/70 and https://github.com/swift-nav/gnss-converters/pull/161 which implement the check.
> EX-472: Reject invalid RTCM antenna height setting values

- package/libsettings/libsettings.mk
- package/sbp_settings_daemon/sbp_settings_daemon/src/settings.c
To avoid further focus on issues indicated by the case that a setting is requested when it does not exist or has not been registered yet.
> Clarify unknown setting read warning [ESD-908]

- package/orion_daemon/overlay/etc/init.d/S82orion_daemon
Avoid more errors on start-up by not attempting to start a service that doesn't exist.  This commit WILL NOT be merged to master.
> Disable orion daemon start-up script [ESD-968]

- package/common_init/overlay/etc/init.d/S79runsvdir
This prevents us from creating an "sv" link which points to nothing
and causes runsvdir to issue warnings about it.
> Fix creation of service dir links [ESD-968]

- package/libpiksi/libpiksi/src/endpoint.c
- package/libpiksi/libpiksi/src/sbp_rx.c
- package/resource_monitor/resource_monitor/src/sbp.c
- package/sbp_protocol/src/sbp_router.yml
- package/sbp_protocol/src/sbp_router_smoothpose.yml
- package/starling_daemon/overlay/etc/endpoint_router/sbp_router_starling.yml
In `pk_endpoint_t` we disconnect clients that fall behind and failed to empty their buffers:
- https://github.com/swift-nav/piksi_buildroot/blob/v2.2.0-release/package/libpiksi/libpiksi/src/endpoint.c#L628
This means that clients that wish to continue receiving data must notice the disconnect and manually reconnect in order to receive data again.  This is presumably something that was handled "under the covers" by nanomsg/zmq.
Tested with `PoseDaemon` and confirmed that initially on start-up it gets behind on servicing data causing it's connection to the `endpoint_router` to be dropped.  Once it reconnects and behind processing data will remain "ahead" and no further reconnects are necessary.
> Reconnect in sbp_rx if we get disconnected [ESD-968]

- package/ports_daemon/ports_daemon/src/ports.c
- package/ports_daemon/ports_daemon/src/ports.h
- package/ports_daemon/ports_daemon/src/ports_daemon.c
- package/ports_daemon/ports_daemon/src/whitelists.c
- package/ports_daemon/ports_daemon/src/whitelists.h
The CAN port settings should be visible if and only if the can_ports flag is on. That flag is set if
[experimental_flags]
can_ports = True
Is in config.ini
Backport of #1081
> hide can settings if can_ports flag not enabled [ESD-883]

- package/common_init/overlay/etc/init.d/common.sh
- package/common_init/overlay/etc/init.d/copy_sys_logs.sh
- package/common_init/overlay/etc/init.d/migrate_sdcard.sh
- package/common_init/overlay/etc/init.d/sdcard.sh
- package/common_init/overlay/lib/mdev/automount.sh
- package/common_init/overlay/usr/bin/service_stopped
- package/common_init/overlay/usr/bin/start_service
- package/standalone_file_logger/standalone_file_logger/src/rotating_logger.cc
F2FS support combined with the IP security work created a bug where standalone logging could not create files if an sdcard was formatted with F2FS.  Fix this by changing the permissions of the top-level directory of the mount point to be like a temporary directory.
Also includes the following fix-ups:
+ Don't allow the `migrate_sdcard` service to run indefinitely if the board doesn't have an sdcard attached
+ Create .sbp files such that the FileIO daemon will be able to read/delete them
https://swift-nav.atlassian.net/browse/ESD-1005
> Allow standalone logging to create files in  F2FS mode [ESD-1005]

- package/standalone_file_logger/standalone_file_logger/src/Makefile
- package/standalone_file_logger/standalone_file_logger/src/rotating_logger.cc
- package/standalone_file_logger/standalone_file_logger/src/rotating_logger.h
- package/standalone_file_logger/standalone_file_logger/src/standalone_file_logger.cc
- package/standalone_file_logger/standalone_file_logger/test/run_rotating_logger_test.cc
When the endpoint router's internal buffer fills up, the connection is silently dropped. This causes both loss of data, and breaks the standalone_logger since it doesn't currently attempt to reconnect. standalone_logger occasionally needs to perform blocking I/O. During these operations, the endpoint router is not being serviced, which ends up overflowing the buffer.
This PR attempts to alleviate the situation by splitting the I/O intensive operations into it's own thread. The endpoint receiver callback will read incoming data into an internal `std::deque< vector<uint8t> * >'. While this will not guarantee that the endpoint router never overflows, it should make it much less likely to occur.
`RotatingLogger::frame_handler` callback has been changed to only copy data from the endpoint …
> Fix standalone logging crash [ESD-981]

- package/common_init/overlay/etc/init.d/S80endpoint_router_sbp
- package/common_init/overlay/etc/init.d/common.sh
We don't want to reset the device when smoothpose isn't running if
* the config won't allow smoothpose to run
* or the binary is missing completely.
#1101 for master
> piksi_ins startup: avoid reset in sdk & some configs

- package/standalone_file_logger/standalone_file_logger/src/Makefile
- package/standalone_file_logger/standalone_file_logger/src/rotating_logger.cc
- package/standalone_file_logger/standalone_file_logger/src/rotating_logger.h
Clang-tidy complained about this being copied but only used once, our "fix" was to change this to a pass by reference, but this causes a crash, probably because we're asking for the address of a temporary `std::function` object?
> Avoid crash by switching back to a regular pass by value [ESD-981]

- package/health_daemon/src/glo_obs_monitor.c
It can take up to 180 seconds for the FW to decode UTC parameters, and SBP GLO base observations cannot be formed before that even if they arrive in base observation stream. During that time, GLO health monitor will spam warnings every 10 seconds, erroneously asking the user to turn GLO acquisition off. 
This is the simplest approach I could think of for reducing warnings in the statistics and not give confusing directions to the user, while still leaving some warnings in place in case base indeed does not send out GLO observations.
Other approach would have been to arm the timeout only after rover observations have at least one GLO present. Or maybe even look at the MSG_UTC_TIME message and confirm UTC parameters are valid.
Issue: https://swift-nav.atlassian.net/browse/EX-329
> EX-329: Change the GLO health monitor timeout to 3 minutes

- scripts/aws-setup.mk
When testing the SDK for release, I still couldn't download the now public upgrade_tool until I used aws s3 cp --no-sign-request
> aws s3 cp; try --no-sign-request if initial cp fails [ESD-1030]

- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
I think if we ever setup a piksi as a base, but still in RTK mode receiving a correction stream from another receiver, the current setup would output both the piksi, and the received correction bias in RTCM out. This is not wanted, we should only output the piksi bias message
@nsirola - does this make sense to you?
> Don't broadcast base bias messages [ESD-1013]

- package/ports_daemon/ports_daemon/src/whitelists.c
To improve Swift Console responsiveness, and add raw IMU msg back to UART1 to work out of the box with IMU tab in the Swift Console to reduce customer confusion.
@silverjam @denniszollo @nicolekelley
> Decimate raw IMU / mag msgs by 50 to improve Swift Console [ESD-1014]

- package/libpiksi/libpiksi/src/util.c
I think we want to check for the .enc file here; otherwise libpiksi will not report Duro Inertial unless the PoseDaemon has already started
> Use encrypted PoseDaemon filepath to determine whether it exists

- package/common_init/overlay/etc/init.d/copy_duro_eeprom.sh
- package/libpiksi/libpiksi/src/util.c
This PR adds a new "is_duro" flag to the new /etc/flags mechanism to communicate Duro status back to the real time firmware in support of can termination.
While at it, I decided to use this same mechanism to determine is Duro in libpiksi.  In this way there is  one-stop shopping and right where EEPROM is copied from filesystem, the string comparison is done.  Rather than look for an exact string, I decided to be forwards compatible to other "duro" values in eeprom which may show up in the future.
The eeprom contents is left in /cfg filesystem as it might prove useful for a new rev of the Piski Multi Hostboard, a customers custom host board, or different DURO SKUs.
> Add an "is duro" flag [ESD-35] [ESD-215]

- package/gnss_convertors/gnss_convertors.mk
Pull in https://github.com/swift-nav/gnss-converters/pull/171
Works on bench: decodes GLO L2 observations from the problematic base and produces RTK Fix.
> EX-518: fix GLO L2 indicator decoding

- fetch_firmware.sh
- fetch_firmware.sh.m4
- requirements.yaml.m4
Allow the bucket that we fetch the firmware from to be manually overridden in the `fetch_firmware.sh` script so that requirement.yaml that gets generated can have a different bucket.  This PR tests these changes: https://github.com/swift-nav/piksi_buildroot/pull/1153.
> Allow piksi_buildroot to pull custom pfwp versions [ESD-1096]

- package/endpoint_adapter/src/endpoint_adapter.c
- package/endpoint_adapter/src/endpoint_adapter.h
- package/endpoint_adapter/src/endpoint_adapter_can.c
- package/endpoint_adapter/src/endpoint_adapter_file.c
- package/endpoint_adapter/src/endpoint_adapter_stdio.c
- package/endpoint_adapter/src/endpoint_adapter_tcp_connect.c
- package/endpoint_adapter/src/endpoint_adapter_tcp_listen.c
- package/endpoint_adapter/src/endpoint_adapter_udp_connect.c
- package/endpoint_adapter/src/endpoint_adapter_udp_listen.c
endpoint_adaptor uses a common POSIX service pattern of calling fork() to spawn a child process when it receives an incoming connection. The call to fork duplicates all open file descriptors, in this case including the socket the server is listening on for new incoming connections. The new child process should immediately close this duplicated socket, but it doesn't. This means the child process can hold the listening socket open for as long as it exists even though it doesn't use it.
If configuration is changed such that the TCP server moves to a different port and then back to the original while the child process is still holding open the origin socket, the server will be unable to restart.
Solution is to simply close the listening socket in newly spawned child processes.
> Close TCP server socket in spawned child processes [ESD-1118]

- package/common_init/overlay/etc/init.d/network_poll.sh
Since `skylark` client has been removed, reports of `WARNING No route to Internet` have popped up. Makes sense since the file doesn't exist anymore.
> Add file check for skylark and ntrip enable filepaths [ESD-1135]

- package/librtcm/librtcm.mk
- package/libswiftnav/libswiftnav.mk
Update the `librtcm` and `libswiftnav` packages to their latest tagged versions.
> EX-516: Update gnss-convertors, librtcm, libswiftnav to latest tagged branches

- package/libpiksi/libpiksi/src/metrics.c
- package/metrics_daemon/metrics_daemon/src/metrics_daemon.c
+ Use advisory file locks so we don't read a metric file while it's being updated
+ Fix casting error in fetch of "nano seconds since epoch" for `pk_metrics_gettime`
+ Use integer division to get absolute values for our number of milliseconds reporting, we don't need to overhead of a float operation.
> Fix overflow bug in time metric reporting [ESD-1134]

- package/common_init/overlay/usr/bin/dump-metrics
- package/common_init/overlay/usr/bin/watch-metrics
- package/endpoint_adapter/src/endpoint_adapter.c
- package/endpoint_router/endpoint_router/src/endpoint_router.c
- package/endpoint_router/endpoint_router/src/endpoint_router.h
- package/ntrip_daemon/src/ntrip_settings.c
- package/rtcm3_in_protocol/src/info_rtcm3_in.c
- package/sbp_protocol/src/framer_sbp.c
- package/sbp_protocol/src/info_sbp.c
- package/skylark_daemon/src/skylark_settings.c
+ Allow an output framer to be specified for the `endpoint_adapter` so that the output filter can process individual SBP messages if they arrive "bunched" in a read from the `endpoint_router` (or whatever the adapter is receiving data from).
+ Fix the `handle_write_*_via_framer*` function so that it can process the whole buffer, even if some of the packets are rejected by the filter.  Previously these functions would bail on an entire read buffer if one frame was rejected.
+ Change `endpoint_router` such that there is one framer per "sub" stream in the router-- this means that any data that arrives on a sub stream will have it's own state for framing so partially written data won't conflict with data from another stream.
+ Spot checked via bench testing and HITL runs
+ Tested `fileio.py` …
> Output framers, per socket framer for router  [ESD-1139]

- package/libpiksi/libpiksi/src/util.c
The rework of `device_is_duro` has been broken for a bit and it seems to be related to the reading of the value from file (not a race condition related to the creation of the file).
I've moved the value read to a previously designed method in the `libpiksi/util` module and added a check that will indicate in the logs if there was any issue with the file itself.
> Use file_read_value for is_duro flag check [ESD-1147]

- package/piksi_leds/src/firmware_state.c
Update the LED to use the new measurement_state message and not the older tracking message
@denniszollo
> [ESD-1194] Fix POS LED behavior

- package/common_init/overlay/etc/init.d/S20flags
To support https://github.com/swift-nav/piksi_firmware_private/pull/2754
Design:
Use existing `detect_piksi_ins` to create a flag (`/etc/flags/ins_active`) using `S20flags` that allow PFWP to mutate its default IMU output behavior. This should not interfere with any `config.ini` defaults set since the default mutation with happen before registration of the setting. Requires that the flag is created before PFWP starts up which is currently satisfied by the init order.
> Create a flag that represents INS configuration being active [ESD-1065]

- board/piksiv3/rootfs-overlay/etc/init.d/S83endpoint_adapter_rpmsg_piksi100
- board/piksiv3/rootfs-overlay/etc/init.d/S83endpoint_adapter_rpmsg_piksi101
- package/common_init/overlay/etc/init.d/S80endpoint_router_sbp
- package/endpoint_adapter/src/endpoint_adapter.c
- package/endpoint_router/endpoint_router.mk
- package/endpoint_router/endpoint_router/src/endpoint_router.c
- package/endpoint_router/endpoint_router/src/endpoint_router.h
- package/endpoint_router/endpoint_router/src/endpoint_router_load.c
- package/endpoint_router/endpoint_router/test/endpoint_router_test.cc
- package/endpoint_router/endpoint_router/test/run_test.yml
- package/endpoint_router/endpoint_router/test/sbp_router_full.yml
- package/endpoint_router/endpoint_router/test/test_router.bash
- package/libpiksi/libpiksi/src/metrics.c
- package/rpmsg_piksi/src/rpmsg_piksi.c
- package/sbp_protocol/src/info_sbp.c
- package/sbp_protocol/src/sbp_router.yml
Addresses a number of messaging issues that can occur under heavy load, primarily we're removing framing support from `endpoint_router` and moving it back into `endpoint_adapter`.  An output framer was also added to the endpoint that receives data from rpmsg, there's a remote possibility that data from the RTOS would be truncated in a particular read if we're under (very) heavy load.
Bench testing and HITL smoke tests.  Testing scenario as follows: (1) start a file upload while Piksi is receiving corrections from a NTRIP service (2) observe that occasionally the console would report packets dropped because one of a sequence of remote obs would be missing.
Apart from the console, remote Piksi obs can be sampled using the following script:
```sh
socat tcp:$THE_PIKSI:55555 - | sbp2json  | jq …
```
> Fix data drops that occurred under heavy load [ESD-1203]

- package/common_init/overlay/etc/init.d/S09sysctl
- package/endpoint_adapter/src/endpoint_adapter.c
- package/libpiksi/libpiksi/include/libpiksi/sbp_pubsub.h
- package/libpiksi/libpiksi/include/libpiksi/sbp_rx.h
- package/libpiksi/libpiksi/include/libpiksi/sbp_tx.h
- package/libpiksi/libpiksi/src/endpoint.c
- package/libpiksi/libpiksi/src/sbp_pubsub.c
- package/libpiksi/libpiksi/src/sbp_rx.c
- package/libpiksi/libpiksi/src/sbp_tx.c
- package/ports_daemon/ports_daemon/src/ports.c
- package/sbp_fileio_daemon/overlay/etc/init.d/S81sbp_fileio_daemon_external
- package/sbp_fileio_daemon/sbp_fileio_daemon/src/main.c
- package/sbp_fileio_daemon/sbp_fileio_daemon/src/sbp_fileio.c
- package/sbp_fileio_daemon/sbp_fileio_daemon/src/sbp_fileio.h
- package/sbp_rtcm3_bridge/src/sbp.c
This adds a new mode to `endpoint_adapter` and `sbp_fileio_daemon` that allow it to bypass the router, thus removing the need for the complications associated with trying to "fast pass" data through the router.  By adding server sockets to `sbp_fileio_daemon` we can also solve the problem of only responding to fileio data on the port it was received on, which avoids the issue where FileIO response data for a TCP connection would flood the UART.
Mostly bench testing with HITL spot checks.  Seeing that this is actually the fastest of all previous methods because it allows FileIO response data to be batched into a large TCP send (rather than a bunch of small ones).  When data flowed through the endpoint_router, then to the `endpoint_adapter` we were forced through a framer at some point, …
> FileIO "bypass" support [ESD-1203]

- scripts/hitl_smoke_test
> Point to the new hitl api URL.

- package/common_init/overlay/etc/init.d/S85network_poll
- package/common_init/overlay/etc/init.d/network_poll.sh
- package/piksi_system_daemon/src/main.c
- scripts/gen-docker-suffix
- Allows the network polling service to be disabled by settings the frequency to zero
- Adds a settings that allows the ping address for the connectivity check to be configured, as such, we're dropping the `114.114.114.114` address
- Bench testing by @silverjam and @switanis to confirm that ping IP can be configured successfully and that setting the frequency to zero successfully disables the service.
> Check for divide by zero, support disabling network check [ESD-1228]

- package/common_init/overlay/etc/init.d/S99reset_boot_counter
If a device did not have a uboot environment, this would brick the device with an incomplete uboot environment. This disables the upgrading, which should disallow bricking a device.
> do not upgrade uboot environment [ESD-1240]

- package/health_daemon/src/baseline_monitor.c
Rate limit to once every 5 minutes from 10 seconds
Increase threshold to 120 km from 80 km
Change to INFO, from WARNING
> Update baseline threshold warning [ESD-1237]

- scripts/release-post-tag
So that https://github.com/swift-nav/piksi-releases Jenkins can pass, support the `NO_WRITE` flag in the `release-post-tag` script.
> Support NO_WRITE in the release post tag script

- Jenkinsfile
Git helpers moved to `ci-jenkins` on the `stable-pbr` tag (https://github.com/swift-nav/ci-jenkins/commits/stable-pbr) -- use `gitHeadHasTag` to gate SDK builds instead of `context.isTagPush`.
The helper `gitHeadHasTag` was tested [here](https://jenkins-test.ci.swift-nav.com/blue/organizations/jenkins/swift-nav%2Fhello-swift/detail/0.0.9/1/pipeline/22), and seems to correctly detect the presence of a tag:
Since `piksi-releases` pushes new commits and tags together this should allow the PBR release build to detect the tag on the branch push, and trigger an SDK build.
> Use gitHeadHasTag to gate SDK build [ESD-46]

- package/piksi_system_daemon/src/main.c
Adds a new ethernet:interface_mode setting to allow for batch updates of all
ethernet settings at once. This prevents the piksi from entering an
invalid IP state during the process of updating settings, and possibly
becoming unreachable.
If the ethernet configuration is in "Config" mode, the ethernet settings can be
changed freely, but will have no effect. When the ethernet configuration
is set to "Active", all settings will be updated at once, and become unmodifiable
until changed back to "Config" mode.
> Add ethernet:interface_mode setting [ESD-1320]

- package/gnss_convertors/gnss_convertors.mk
- package/librtcm/librtcm.mk
- package/libsbp/libsbp.mk
Update `librtcm` and `gnss-converters` to latest releases to pull in https://github.com/swift-nav/librtcm/pull/80 and https://github.com/swift-nav/gnss-converters/pull/192.
Update `libsbp` to latest release to pull in the OSR message support.
All HITL tests green with some runs also in the msm7 and Orion scenarios:
https://hitl-viewer.ce.swiftnav.com/summary_type=q50&metrics_preset=pass_fail&scenario=live-roof-650-townsend,live-roof-650-townsend-msm7,live-roof-650-townsend-orion,live-roof-650-townsend-dropouts-zero-baseline,live-roof-650-townsend-post&build_type=buildroot_pr&firmware_versions=v2.2.0-develop-2019051319-14-g6a6518dec&groupby_key=scenario_name&display_type=table
> EX-578: update librtcm, gnss-converters, and libsbp to latest versions

- package/ports_daemon/ports_daemon/src/ports.c
Certain CAN protocols such as J1939 are only applicable to the CAN ports
on the piksi. We should not be allowed to set the USB, UDP/TCP, etc.
ports into J1939 mode.
This commit accomplishes that by introducing protocol blacklists to the
ports daemon. Each port_config_t has a list of strings of protocol names
that are blacklisted on that port.
A list of all protocols is stored in a "global" array. Each port needs
to maintain their own list due to potential blacklisted protocols. Two
additional fields have been added to port_config_t to store the mapping
between these two lists.
> Add protocol blacklist to port mode selection [ESD-1289]

- Jenkinsfile
We used the stable-pbr tag during the switchover to jenkins so that it was easier to publish fixes during that process.
Now that the switch has been done for a while, we can return to using the "stable" tag, which makes sure we pull in any necessary future updates to the shared libs.
> Switch back to using the stable tag for Jenkins shared libs

- Jenkinsfile
> Merge cherry-picks from refs/heads/v2.3.0-release (13a51af15) into master: Switch back to using the stable tag for Jenkins shared libs (#1280)

- package/gnss_convertors/gnss_convertors.mk
- package/librtcm/librtcm.mk
- package/libsbp/libsbp.mk
- package/libswiftnav/libswiftnav.mk
- package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
the current gnss-converters code can generate a MSM message for QZSS but fails to handle it in https://github.com/swift-nav/gnss-converters/blob/master/c/src/sbp_rtcm3.c#L92
Additional cmake changes in all repos require submodules to be pulled in as well..
> Use new gnss-converters tag [ESD-1393]

- package/piksi_system_daemon/src/main.c
master version of #1273 
If ethernet:interface_mode is persisted as "Config", the post settings register step in `piksi_system_daemon` overrides it to "Active", which creates an inconsistency between the local setting value and `sbp_settings_daemon` cached value. This PR removes the value override and allows a device to boot in "Config" mode.
It could be argued as a feature to be able to boot without updating the ethernet function but I would consider it to be quite risky considering a customer can forget which mode the ethernet settings are in and persist without much thought. Therefore a companion PR should be created to warn the user via console in the case that the mode is "Config" when attempting to persist the settings.
> Don't change interface_mode outside settings interaction [ESD-1364]

- package/health_daemon/src/gnss_time_monitor.c
Attempt to fix: https://swift-nav.atlassian.net/browse/ESD-1432
> Don't filter MSG_GPS_TIME based on sender id in GNSS time monitor [ESD-1432]

- package/libpiksi/libpiksi/src/sha256.c
- package/ota_daemon/src/ota_daemon.c
- package/ota_daemon/src/ota_settings.c
- package/ports_daemon/ports_daemon/src/ports.c
- package/sbp_fileio_daemon/overlay/etc/init.d/S81sbp_fileio_daemon_external
- scripts/docker.mk
+ FileIO support was omitted for tcp_client0 and tcp_client1 during the transition to the faster fileio scheme, add it in so that FileIO will work over these interfaces
+ Add in misc fix-ups for OTA: re-order settings so that on start-up the daemon will accept the OTA URL (the daemon must be in a disabled state before it will allow the URL to change)-- so enable it last.
+ Make sha256sum_cmp not assert when it's conditions aren't met so whatever's using it won't crash
> Re-enable FileIO on tcp_client{0,1}, OTA fix-ups [ESD-1506]

- package/libpiksi/libpiksi/src/sha256.c
- package/ota_daemon/src/ota_daemon.c
- package/ota_daemon/src/ota_settings.c
- package/ports_daemon/ports_daemon/src/ports.c
- package/sbp_fileio_daemon/overlay/etc/init.d/S81sbp_fileio_daemon_external
- scripts/docker.mk
> Merge cherry-picks from refs/heads/v2.3.0-release (2713b61f1) into master: Re-enable FileIO on tcp_client{0,1}, OTA fix-ups [ESD-1506] (#1309)

- .gitignore
- Makefile
- scripts/docker.mk
- scripts/env-setup.mk
- scripts/ssh_unix_socket
This allows less things to have to match-up between the remote docker host (set via DOCKER_HOST) and the local machine.
In the same vein, this also adds support for a `.env.mk` to setup environment variables within the make system to setup the environment variables that allow the `DOCKER_HOST` support to be more generic.
For example:
```
export PBR_BUILD_USER_NAME=ubuntu
export PBR_BUILD_USER_HOME=/home/$(PBR_BUILD_USER_NAME)
export PBR_BUILD_USER_UID=1001
export PBR_BUILD_USER_GID=1002
export PBR_BUILD_SSH_AUTH_SOCK=$(PBR_BUILD_USER_HOME)/.pbr_ssh_auth_sock
export VITANI=10.1.23.184
export DOCKER_HOST=tcp://$(VITANI):2375
export DISABLE_NIXOS_SUPPORT=y
```
> Further generalize support for docker-sync with a remote docker host
