swift-nav/piksi_buildroot

package/zmq_adapter/src/Makefile, package/zmq_adapter/src/zmq_adapter.c
Adds timeouts, resets, warnings to REQ / REP sockets.
/cc @gsmcmullin
=> Improve robustness of REQ / REP

package/zmq_adapter/src/zmq_adapter.c
This should cause all the forked children to close when a signal is sent to the parent.
=> Forward signals to child processes

package/rpmsg_piksi/src/rpmsg_piksi.c
- Allows infrastructure to be started before the firmware boots (avoids race condition)
- Decouples firmware from the linux infrastructure so that it may be stopped / restarted independently
=> Create char devs on init, attach rpmsg when probed

.travis.yml, publish.sh
Avoid multi-part upload for anonymous.
=> Direct put for anonymous

board/piksiv3/rootfs-overlay/etc/init.d/S84piksi_fpga
- Copy `piksi_fpga.bit` from SD card if present
- Configure FPGA using `xdevcfg` driver
=> Add piksi_fpga init script

board/piksiv3/piksiv3.dtsi, board/piksiv3/piksiv3_evt1.dts, board/piksiv3/piksiv3_evt2.dts, board/piksiv3/post_image.sh, configs/piksiv3_defconfig, package/uboot_custom/uboot_custom.mk
- DTS for microzed, evt1, evt2
- Add uart0 and FPGA IRQs 8-15
TODO:
/cc @gsmcmullin
=> Add EVT1 and EVT2 configs

board/piksiv3/rootfs-overlay/etc/init.d/S83zmq_adapter_uart1, board/piksiv3/rootfs-overlay/etc/init.d/adapter_uart.inc.sh
- Add `-onlcr` to stty flags
- Change UART1 baud rate to 115k
/cc @gsmcmullin
=> UART changes

package/zmq_router/src/zmq_router_sbp.c
=> zmq_router: Block internal only SBP messages.

board/piksiv3/piksiv3.dtsi
=> Transfer control of I2C to firmware

package/uboot_custom/uboot_custom.mk
=> Update uboot hash

.travis.yml
=> Fix upload of EVT2 binaries

board/piksiv3/rootfs-overlay/etc/init.d/S75dev_boot, package/factory_data_tool/src/factory_data_tool.c, package/uboot_custom/uboot_custom.mk
Update `factory_data_tool` and others to support new factory data parameters. Replace `serial_number` with `uuid`.
TODO:
/cc @swift-nav/firmware @axlan
=> Update factory data

board/piksiv3/piksiv3_prod.dts
Part of this space will be used for dev U-Boot environment.
=> Reserve 1MB at the end of both standard partitions

board/piksiv3/post_image.sh, fetch_firmware.sh
Proposal for semantic filenaming if the final artifact.  All public facing builds would have semantic versioning in format vX.XX which are pushed as annotated tags.
/cc @fnoble @jacobmcnamee
=> File nameing

package/libsbp/libsbp.mk, package/sbp_settings_daemon/src/main.c, package/sbp_settings_daemon/src/settings.c, package/sbp_settings_daemon/src/settings.h
I put this in `sbp_settings_daemon` rather than `piksi_system_daemon` as it needs to reset the settings if requested.
=> SBP reset implementation

board/piksiv3/piksiv3_prod.dts, package/uboot_custom/uboot_custom.mk
Maximum QSPI output clock is 40MHz without feedback pin connected.
TODO: 
=> Update QSPI part and max clock rate in DTS

package/sbp_settings_daemon/src/settings.c
Fix for https://github.com/swift-nav/piksi_v3_bug_tracking/issues/166
/cc @denniszollo
=> sbp_settings_daemon: Don't allow duplicate settings.

board/piksiv3/rootfs-overlay/etc/init.d/S83zmq_adapter_rpmsg_piksi101, board/piksiv3/rootfs-overlay/etc/init.d/S83zmq_adapter_tcp_listen_nmea, board/piksiv3/rootfs-overlay/etc/init.d/S83zmq_adapter_tcp_listen_sbp, board/piksiv3/rootfs-overlay/etc/init.d/S83zmq_adapter_uart0, board/piksiv3/rootfs-overlay/etc/init.d/S83zmq_adapter_uart1, board/piksiv3/rootfs-overlay/etc/init.d/adapter_uart.inc.sh, board/piksiv3/rootfs-overlay/etc/monitrc, package/piksi_system_daemon/src/main.c, package/zmq_router/src/Makefile, package/zmq_router/src/zmq_router.c, package/zmq_router/src/zmq_router_nmea.c
=> NMEA mode setting for UARTs

board/piksiv3/rootfs-overlay/etc/init.d/adapter_uart.inc.sh
=> Gserial fix (for reals this time?)

board/piksiv3/rootfs-overlay/etc/init.d/adapter_uart.inc.sh
Duplicate of #93 and #94 for the master branch.
=> GSerial fix (master branch)

board/piksiv3/rootfs-overlay/etc/init.d/usb_upgrade.sh, fetch_firmware.sh
Also update firmware and NAP pointers to master.
=> Usb upgrade efi master

package/libsbp_zmq/src/sbp_zmq.c, package/piksi_system_daemon/src/main.c
Release version of https://github.com/swift-nav/piksi_buildroot/pull/102
Resolves swift-nav/piksi_v3_bug_tracking#197
=> Fix UART port mode and baud rate settings (release)

package/piksi_system_daemon/src/main.c, package/zmq_adapter/src/zmq_adapter.c, package/zmq_adapter/src/zmq_adapter_file.c, package/zmq_adapter/src/zmq_adapter_tcp_listen.c
Release version of https://github.com/swift-nav/piksi_buildroot/pull/103
=> Improve signal handling in ZMQ adapter (release)

package/piksi_system_daemon/src/main.c, package/zmq_adapter/src/zmq_adapter.c, package/zmq_adapter/src/zmq_adapter_file.c, package/zmq_adapter/src/zmq_adapter_tcp_listen.c
Resolves issue where child processes were not always properly terminated.
TODO:
=> Improve signal handling in ZMQ adapter (master)

release_notes.txt
@jdormoy
@zakaswift   
@jacobmcnamee 
@switanis 
@jkretzmer 
-  Plan is to commit release notes to release branch and work on them as we finalize the release.  These release notes will be derived from an autogenerated more detailed changelog.  They will be a running document with all prior releases below.
-  Release notes will have the following sections:
- features (repeated each time, highlighting new or changed features)
- changes  (changes that aren't really features)
- fixes (fixed bugs)
- known issues 
- notes
- Our "publishing" process will put the release binary and release notes up on our website for our customers. 
- Plain text (rather than markdown) is used since it is intended to go places beyond github or a web browser
=> Add 1.0.11 release notes

README.md
README instructions needed to be updated for new use of git submodules.
=> Update README for submodules

board/piksiv3/rootfs-overlay/etc/init.d/S85zmq_file_logger
=> Whoops: remove accidental rootfs rotating file logger commit.

board/piksiv3/rootfs-overlay/etc/init.d/usb_upgrade.sh
we broke the upgrade
I don't want to do this.  It is bad for user experience.
=> don't kill anything during upgrade

board/piksiv3/rootfs-overlay/etc/init.d/usb_upgrade.sh
Release version of https://github.com/swift-nav/piksi_buildroot/pull/177.
=> don't kill anything during upgrade [release]

board/piksiv3/rootfs-overlay/etc/init.d/reset2defaults.sh, board/piksiv3/rootfs-overlay/etc/init.d/s84reset2defaults
This should provide another way for a user to recover communication with a device should he save settings that bric a piksi
/cc @switanis @jkretzmer @jacobmcnamee
=> Add process to reset2default settings if a magic file is found on flash drive

board/piksiv3/rootfs-overlay/etc/init.d/reset2defaults.sh, board/piksiv3/rootfs-overlay/etc/init.d/s84reset2defaults
Release version of https://github.com/swift-nav/piksi_buildroot/pull/175
=> Reset to defaults [release]

package/sbp_rtcm3_bridge/src/sbp.c, package/sbp_rtcm3_bridge/src/sbp_rtcm3.c, package/sbp_rtcm3_bridge/src/sbp_rtcm3.h, package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Adding sbp gps time message callback to RTCM3 to SBP decoder
=> Add sbp callback for time message

package/sbp_rtcm3_bridge/src/sbp.c, package/sbp_rtcm3_bridge/src/sbp_rtcm3.c, package/sbp_rtcm3_bridge/src/sbp_rtcm3.h, package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
=> Add gps time support release

board/piksiv3/rootfs-overlay/etc/init.d/usb_upgrade.sh, fetch_firmware.sh
Turn off firmware zeromq adapter again to silence extraneous information.
@cbeighley
=> Zeromq upgrade turn off

README.md
=> Update readme for Makefile / Dockerfile changes

.travis.yml, Makefile
Don't run the cmake test.
/cc @cbeighley
=> Take out the cmake test

package/piksi_system_daemon/src/main.c
=> Configure USB0 TTY [release]

.travis.yml, Makefile, fetch_firmware.sh
Remove microzed building and publishing.
/cc @cbeighley @wltr
=> Remove microzed

package/zmq_adapter/src/Makefile, package/zmq_adapter/src/filter_sbp.c, package/zmq_adapter/src/framer_none.c, package/zmq_adapter/src/framer_sbp.c, package/zmq_adapter/src/zmq_adapter.c, package/zmq_adapter/src/zmq_adapter.h, package/zmq_adapter/src/zmq_adapter_file.c, package/zmq_adapter/src/zmq_adapter_stdio.c, package/zmq_adapter/src/zmq_adapter_tcp_listen.c
=> ZMQ adapter improvements [release]

package/nmea_protocol/src/info_nmea.c, package/rtcm3_protocol/src/info_rtcm3.c
Master version of https://github.com/swift-nav/piksi_buildroot/pull/225.
=> Update protocol settings naming to be the same as v1.1 release

package/piksi_system_daemon/src/main.c
@cbeighley @switanis @jacobmcnamee
=> system_daemon: change port model labels to indicate directionality

package/libsbp/libsbp.mk, package/sbp_rtcm3_bridge/src/sbp_rtcm3.c
update member name in sbp_rtcm3_bridge
=> Update libsbp to 2.2.0

package/piksi_system_daemon/src/main.c
Depends on https://github.com/swift-nav/libsbp/pull/449
=> Added handling of network state request

board/piksiv3/post_build.sh, board/piksiv3/post_image.sh
=> Fail if HW_CONFIG is not defined in post_build.sh and post_image.sh

package/sbp_rtcm3_bridge/src/sbp_rtcm3.c
release candidate off this fix https://github.com/swift-nav/piksi_buildroot/pull/243 for this issue https://github.com/swift-nav/piksi_v3_bug_tracking/issues/430
=> Rounding fix for RTCM

package/sbp_rtcm3_bridge/src/sbp_rtcm3.c, package/sbp_rtcm3_bridge/src/sbp_rtcm3.h, package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
RELEASE PR for this issue https://github.com/swift-nav/piksi_v3_bug_tracking/issues/424
=> Debug guards for sbp logging

package/sbp_rtcm3_bridge/sbp_rtcm3_bridge/src/sbp_rtcm3.c, package/sbp_rtcm3_bridge/sbp_rtcm3_bridge/src/sbp_rtcm3.h, package/sbp_rtcm3_bridge/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Master PR for this issue https://github.com/swift-nav/piksi_v3_bug_tracking/issues/424
@mfine @jacobmcnamee could you guys check I haven't done anything stupid in this PR? I'll put up another one for the release shortly. I haven't bench tested, still waiting for the build
=> Add debugging guards to sbp3_rtcm_bridge

board/piksiv3/rootfs-overlay/etc/init.d/usb_upgrade.sh, package/upgrade_tool/src/common.h, package/upgrade_tool/src/mtd.c, package/upgrade_tool/src/upgrade_tool.c
Read, write, and erase flash in chunks so that accesses from other processes do not block for significant amounts of time. Also adds % complete debug logging for erase and write operations.
TODO:
/cc @swift-nav/firmware @denniszollo
=> Upgrade tool: read, write, erase flash in chunks

package/sbp_rtcm3_bridge/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
missed in this PR https://github.com/swift-nav/piksi_buildroot/pull/241
=> Add missing declaration

package/piksi_system_daemon/src/main.c, package/piksi_system_daemon/src/whitelists.c, package/zmq_adapter/src/Makefile, package/zmq_adapter/src/zmq_adapter.c, package/zmq_adapter/src/zmq_adapter.h, package/zmq_adapter/src/zmq_adapter_file.c, package/zmq_adapter/src/zmq_adapter_stdio.c, package/zmq_adapter/src/zmq_adapter_tcp_connect.c, package/zmq_adapter/src/zmq_adapter_tcp_listen.c
Add `--tcp-c` option to ZMQ adapter to support TCP client connection mode. In this mode the adapter will attempt to connect to a TCP server, retrying every 10s.
Also enables configuration of TCP server port numbers.
TODO:
/cc @swift-nav/firmware @jkretzmer
=> TCP connect support, configurable TCP server port

package/sbp_rtcm3_bridge/sbp_rtcm3_bridge/src/sbp_rtcm3.c
master version of https://github.com/swift-nav/piksi_buildroot/pull/249
=> Encode MAX size when appropriate

package/libnetwork/src/libnetwork.c
Don't reuse connections and log out responses.
=> Don't reuse connections, log out response

package/libnetwork/src/libnetwork.c
Master version of https://github.com/swift-nav/piksi_buildroot/pull/253.
=> Network options to improve failing fast

board/piksiv3/rootfs-overlay/etc/init.d/S75dev_boot
Release version of https://github.com/swift-nav/piksi_buildroot/pull/255. DEV boots config if present.
=> DEV boot config.ini if present

package/sbp_rtcm3_bridge/src/sbp_rtcm3.c
This is to not process 1001 and 1003 messages.
=> exit on 1001 or 1003 messages

Makefile
/cc @swift-nav/firmware @denniszollo @anth-cole
=> Add clean targets to Makefile

fetch_firmware.sh.m4
To support the swiftnav-releases bucket.
=> Move bucket to swiftnav-releases

fetch_firmware.sh, fetch_firmware.sh.m4
Try a no sign request first.
/cc @jacobmcnamee
=> No sign request

fetch_firmware.sh, fetch_firmware.sh.m4
Master version of https://github.com/swift-nav/piksi_buildroot/pull/273.
=> Try a no signed request first

release_notes.txt
@cbeighley @switanis @jdormoy @swift-nav/business
=> v1.1 release notes

package/sbp_rtcm3_bridge/sbp_rtcm3_bridge/src/sbp_rtcm3.c
This PR does two things
1. Suppress messages 1001 and 1003 like on release until we can agree on a method to resolve the millisecond ambiguity
2. Add a gate to not decode RTCM messages until after we've received a time message from the rover to resolve the WN uncertainty - pulled in from https://github.com/swift-nav/piksi_buildroot/compare/v1.1.0-release...mfine/gps-time-updated#diff-7315a85eb99edefc07a6c29f25b699c5R38
@mfine
=> Fixes for master on RTCM handling

release_notes.txt
v1.1.28 release notice updated for release
=> v1.1.28 release notice updated for release

fetch_firmware.sh
=> Latest fw 07 07

package/piksi_system_daemon/src/async-child.c, package/piksi_system_daemon/src/async-child.h, package/piksi_system_daemon/src/cellmodem.c, package/piksi_system_daemon/src/cellmodem.h, package/piksi_system_daemon/src/main.c
=> Respawn pppd (master branch)

package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
This adds the UTC message callback support for enabling GLO observations over RTCM. This is needed to derive the leap second and from that time match the GPS and GLO observations.
=> Add support for deriving leap second for GLO processing

package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Move up the converter init. Also bring in:
https://github.com/swift-nav/gnss-converters/pull/45
/cc @anth-cole
=> Move up the converter init.

package/gnss_convertors/gnss_convertors.mk
Update gnss-convertors for bugfix for https://github.com/swift-nav/piksi_v3_bug_tracking/issues/700
=> Update gnss convertors RELEASE

package/gnss_convertors/gnss_convertors.mk
=> Update gnss_convertors version

board/piksiv3/rootfs-overlay/etc/monitrc
Refers to https://github.com/swift-nav/piksi_v3_bug_tracking/issues/701
=> Restart the system if piksi_system_daemon dies

.travis.yml
=> Build branches only for master and 1.2.0

fetch_firmware.sh
This reverts commit 89d77446885412f18e010729fa0085cc87ce4fd3 which was accidental
=> Revert "update fetch_firmwares for PR:v1.2.6-3-gaef2fdc1"

package/piksi_system_daemon/piksi_system_daemon/src/whitelists.c
Add the heading message to the default whitelist on uart1.
/cc @denniszollo @switanis
=> Add HEADING to the default whitelist on uart1

package/piksi_system_daemon/piksi_system_daemon/src/ports.c, package/piksi_system_daemon/piksi_system_daemon/src/whitelists.c
Pick up:
https://github.com/swift-nav/piksi_buildroot/pull/356
https://github.com/swift-nav/piksi_buildroot/pull/372
from v1.2 release.
/cc @denniszollo
=> Pick up whitelist changes from v1.2.0 release.

package/piksi_system_daemon/piksi_system_daemon/src/ports.c, package/piksi_system_daemon/piksi_system_daemon/src/whitelists.c, package/zmq_adapter/src/Makefile, package/zmq_adapter/src/zmq_adapter.c, package/zmq_adapter/src/zmq_adapter_udp_connect.c, package/zmq_adapter/src/zmq_adapter_udp_listen.c
Similar to TCP client/server, but in UDP.
=> UDP client/server

board/piksiv3/rootfs-overlay/etc/monitrc, package/uboot_custom/uboot_custom.mk
Incorporates the following fixes:
- https://github.com/swift-nav/piksi_buildroot/pull/346
- https://github.com/swift-nav/piksi_buildroot/pull/340
Note, does not include #342, this was for release only.
See also https://docs.google.com/spreadsheets/d/1nKJ-hcJRW8a43HwpKi4OXjX1O-vcRZSJE-4dlHuMOGA/edit#gid=0
=> Leftover fixes from v1.2 release [master]

board/piksiv3/rootfs-overlay/etc/init.d/S38usb_gadget, board/piksiv3/rootfs-overlay/etc/monitrc, package/uboot_custom/uboot_custom.mk
Incorporates the following fixes:
- https://github.com/swift-nav/piksi_buildroot/pull/346
- https://github.com/swift-nav/piksi_buildroot/pull/342
- https://github.com/swift-nav/piksi_buildroot/pull/340
See also https://docs.google.com/spreadsheets/d/1nKJ-hcJRW8a43HwpKi4OXjX1O-vcRZSJE-4dlHuMOGA/edit#gid=0
=> Leftover fixes from v1.2 release [release]

package/gnss_convertors/gnss_convertors.mk, package/librtcm/librtcm.mk, package/libsbp/libsbp.mk
Update Librtcm and gnss-convertors to support the glonass IFB messages
@scarcanague
=> Add GLO IFB support

package/libnetwork/src/libnetwork.c
Fix up the network headers.
/cc @silverjam
=> Sort out headers.

board/piksiv3/rootfs-overlay/etc/monitrc
=> Disable monitd web interface port

LICENSE
Will need to merge to master too.
=> Add LGPLv3 LICENSE to the project

Makefile, docker/Dockerfile, docker/docker.mk, docker/entrypoint.sh
Fix-up permissions so that a build from clean by a non-root account works correctly.
cc: @jck
=> Fix permissions for a clean linux build

package/zmq_adapter/src/zmq_adapter_udp_connect.c
Allow UDP broadcast on the client for master.
/cc @srossel @mfine @cbeighley
=> Allow UDP broadcast master

package/zmq_adapter/src/zmq_adapter_tcp_listen.c, package/zmq_adapter/src/zmq_adapter_udp_connect.c, package/zmq_adapter/src/zmq_adapter_udp_listen.c
Minor nits around networking.
/cc @silverjam
=> nits around networking

Makefile, docker/Dockerfile, docker/docker.mk, docker/entrypoint.sh
=> docker: GID fixes, add targets for flushing rootfs and wiping docker

package/libnetwork/src/libnetwork.c
Fix the client headers for the clients.
/cc @silverjam
=> Fix client headers

publish.sh
Don't write publicly.
/cc @silverjam
=> Stop doing public writes.

publish.sh
Send pull requests to the pull request bucket.
/cc @silverjam
=> Send pull request artifacts to the pull requests bucket.

package/gnss_convertors/gnss_convertors.mk
=> Add topcon 1033 support in gnss-convertors

package/piksi_ins/piksi_ins.mk
Updated piksi_ins SHA to reflect build changes made for testing on 10Jan2018
=> Updated piksi_ins SHA

package/piksi_leds/src/manage_led.c
For Duro Cell Modem solution S1.
This doesn't actually poll the network, but reads from a file `/var/network_available`.  That file must contain a '0' or a '1' filled in by another process.
For task https://github.com/swift-nav/firmware_team_planning/issues/430
=> piksi_leds: Invert link LED when network is availble.

package/libpiksi/libpiksi/src/settings.c, package/libsbp/libsbp.mk, package/piksi_system_daemon/piksi_system_daemon/src/whitelists.c, package/sbp_settings_daemon/sbp_settings_daemon/src/settings.c
=> Implement SBP settings write response

package/piksi_leds/src/led_adp8866.c, package/piksi_leds/src/manage_led.c
Master version of #459 
cc @gsmcmullin
=> piksi_leds fixes from v1.4

.clang-format, package/health_daemon/docs/README.md, package/health_daemon/src/Makefile, package/health_daemon/src/baseline_monitor.c, package/health_daemon/src/baseline_monitor.h, package/health_daemon/src/glo_bias_monitor.c, package/health_daemon/src/glo_bias_monitor.h, package/health_daemon/src/glo_obs_monitor.c, package/health_daemon/src/glo_obs_monitor.h, package/health_daemon/src/health_daemon.c, package/health_daemon/src/health_monitor.c, package/health_daemon/src/health_monitor.h, package/health_daemon/src/utils.c, package/health_daemon/src/utils.h
Duplicate of Glonass Health Monitoring for 1.4 #463
Squashed for cleanliness, you can see full commit
logs in v1.4 branch 8cf91e5..24b07ea
=> DEV - Glonass Health Monitoring for 1.4

package/piksi_system_daemon/piksi_system_daemon/src/whitelists.c
For https://github.com/swift-nav/piksi_v3_bug_tracking/issues/992.
=> Add UART1 whitelist to TCP server/client and UDP client [release]

package/health_daemon/src/glo_obs_monitor.c
Glo obs warning was firing off even when not connected to a base station.
Added a check for base station observations that gates this warning which is set in the message callback if any obs msg with the forwarding sender id is received.
swift-nav/piksi_v3_bug_tracking#999
=> Fix glo obs warning when not receiving base station obs

package/health_daemon/src/glo_obs_monitor.c
This is the dev PR for swift-nav/piksi_buildroot#474:
"Glo obs warning was firing off even when not connected to a base station.
Added a check for base station observations that gates this warning which is set in the message callback if any obs msg with the forwarding sender id is received."
=> [DEV] Fix glo obs warning when not receiving base station obs

package/piksi_system_daemon/piksi_system_daemon/src/whitelists.c
For https://github.com/swift-nav/piksi_v3_bug_tracking/issues/992.
=> Add UART1 whitelist to TCP server/client and UDP client [master]

package/libnetwork/src/libnetwork.c
If an ntrip connection finishes with response code
and no data received we assume that the endpoint
was expecting a GGA message in order to begin the
transmission of VRS corrections. This does not
cover the case where an RTCM message indicating
such a requirement is sent.
Summary of features added:
* A response code data member and check function
* The check function is executed on completion
of a network request that did not have a curl
error and had a non-zero response code
* An implementation of this feature to warn when
the ntrip download ends with 200 and no data
* The warning will only be issued once as it is
a large message and the network request may
repeat many times with the same result
Addresses swift-nav/piksi_v3_bug_tracking#1012
=> Add Warning when NTRIP Connection Ends with 200

package/libnetwork/src/libnetwork.c
If an ntrip connection finishes with response code
and no data received we assume that the endpoint
was expecting a GGA message in order to begin the
transmission of VRS corrections. This does not
cover the case where an RTCM message indicating
such a requirement is sent.
Summary of features added:
* A response code data member and check function
* The check function is executed on completion
of a network request that did not have a curl
error and had a non-zero response code
* An implementation of this feature to warn when
the ntrip download ends with 200 and no data
* The warning will only be issued once as it is
a large message and the network request may
repeat many times with the same result
Addresses swift-nav/piksi_v3_bug_tracking#1012
Dev PR for #487
=> [DEV] Add Warning when NTRIP Connection Ends with 200

package/libnetwork/src/libnetwork.c
Master version of https://github.com/swift-nav/piksi_buildroot/pull/489.
=> Request errors -> warnings

package/health_daemon/src/glo_bias_monitor.c, package/health_daemon/src/glo_obs_monitor.c
swift-nav/piksi_v3_bug_tracking#1029
=> Add info for suppressing GLONASS warnings.

package/health_daemon/src/glo_bias_monitor.c, package/health_daemon/src/glo_obs_monitor.c
swift-nav/piksi_v3_bug_tracking#1029
Dev PR for #497
=> [DEV] Add info for suppressing GLONASS warnings.

package/piksi_system_daemon/piksi_system_daemon/src/whitelists.c
Change the SPECAN message whitelist.
/cc @denniszollo @mbavaro
=> New SPECAN message.

package/piksi_system_daemon/piksi_system_daemon/src/whitelists.c
Change the SPECAN message whitelist.
/cc @denniszollo @mbavaro
=> New SPECAN message

package/health_daemon/src/baseline_monitor.c
was debugging https://github.com/swift-nav/piksi_v3_bug_tracking/issues/985 and I thought these would improve a bit
=> Small changes around baseline monitor [release v1.4]

release_notes.txt
/cc @cbeighley @nicolekelley @akshaybandiwdekar 
Starting release notes brainstorm after reviewing each commit message from v1.3 release cycle.
=> V1.3 release notes

package/sbp_rtcm3_bridge/src/sbp.c, package/sbp_rtcm3_bridge/src/sbp.h, package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Copy-paste fix for watching simulator in rtcm3_bridge
swift-nav/piksi_v3_bug_tracking#998
PR for master here: #504
=> Added short term setting watch for simulation in rtcm3 bridge.

package/piksi_system_daemon/piksi_system_daemon/src/cellmodem.c
For https://github.com/swift-nav/piksi_v3_bug_tracking/issues/1075
=> Change default APN to 'hologram'.

package/libnetwork/src/libnetwork.c, package/libnetwork/src/libnetwork.h, package/ntrip_daemon/src/ntrip_daemon.c, package/piksi_system_daemon/piksi_system_daemon/src/ntrip.c
=> Introduce separate username and password settings for ntrip

package/sbp_rtcm3_bridge/src/sbp.c, package/sbp_rtcm3_bridge/src/sbp.h, package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
=> [DEV] Refactor rtcm3 bridge simulator watcher

package/gnss_convertors/gnss_convertors.mk
fix for #1091 issue in spain when 1012 message comes first.
=> Update gnss-convertor version

package/health_daemon/src/baseline_monitor.c
master version of https://github.com/swift-nav/piksi_buildroot/pull/502
=> Small changes around baseline monitor [master]

package/sbp_protocol/src/sbp_router.yml
=> allow settings write response to go to sbp_settings_daemon

scripts/comment.sh, scripts/hitl_smoke_test.sh
Fix the links to use the correct type
@silverjam
=> fix HITL Viewer links

package/piksi_system_daemon/piksi_system_daemon/src/whitelists.c
Fixes https://swift-nav.atlassian.net/browse/DEVC-449
=> Whitelist SBAS raw message [1.5.x]

package/piksi_system_daemon/piksi_system_daemon/src/whitelists.c
Fixes https://swift-nav.atlassian.net/browse/DEVC-449
=> Whitelist SBAS raw message [master]

package/libnetwork/src/libnetwork.c, package/libnetwork/src/libnetwork.h, package/libpiksi/libpiksi/include/libpiksi/logging.h, package/libpiksi/libpiksi/src/logging.c, package/piksi_system_daemon/piksi_system_daemon/src/skylark.c, package/skylark_upload_daemon/src/skylark_upload_daemon.c
Release 1.5 version of https://github.com/swift-nav/piksi_buildroot/pull/569
=> Rate limit libnetwork errors [DEVC-381] [v1.5.x]

board/piksiv3/rootfs-overlay/etc/init.d/S80zmq_router_sbp, package/sbp_protocol/src/sbp_router.yml, package/sbp_protocol/src/sbp_router_smoothpose.yml
=> Changed routing to handle GNSS and INS data at the same time

board/piksiv3/rootfs-overlay/etc/init.d/S75dev_boot, board/piksiv3/rootfs-overlay/etc/init.d/copy_from.sh, board/piksiv3/rootfs-overlay/usr/bin/chat_command, board/piksiv3/rootfs-overlay/usr/bin/kill_chat_command, package/cell_modem_daemon/overlay/etc/init.d/kill_pppd_service, package/cell_modem_daemon/src/cell_modem_settings.c
Port of PR #599 for master.  The fixes to async_output_cb are unnecessary since the code was deleted.
=>  Port PR #599 from v1.5: pppd cleanup fixes [DEVC-321]

.travis.yml, scripts/generate_requirements.sh, scripts/hitl_smoke_test.sh
To support scheduled testing in HITL on master / release builds
=> always generate requirements.yaml

package/cell_modem_daemon/src/cell_modem_inotify.c, package/cell_modem_daemon/src/cell_modem_settings.c, package/cell_modem_daemon/src/cell_modem_settings.h
=> [DEVC-675] Add probe retries timer callback for device override during boot period [master]

package/ports_daemon/ports_daemon/src/whitelists.c
This PR whitelists the new slimmer SBP ephemeris messages.
https://github.com/swift-nav/libsbp/pull/564
https://github.com/swift-nav/libsbp/pull/563
https://github.com/swift-nav/libsbp/pull/561
=> Whitelist new SBP ephe messages

board/piksiv3/rootfs-overlay/etc/init.d/S84piksi_fpga
@silverjam how would I go about testing this locally without rebuilding the entire image?
=> Try 3 times

package/libnetwork/src/libnetwork.c
GGA sentence upload support leaked a file descriptor, causing uploads to fail when 1k descriptors where allocated/leaked.  Fix this and add support for uploading the last cached GGA sentence if we fail to read from the file where the GGA sentence is stored.
Ran overnight with ntrip enabled on an endpoint that requires GGA.
=> Fix for continuous GGA upload [DEVC-708]

package/gnss_convertors/gnss_convertors.mk, package/librtcm/librtcm.mk
Pulls in https://github.com/swift-nav/librtcm/pull/41
Check for out of range FCN values in legacy GLONASS observation messages
=> Pull in librtcm GLONASS FCN range checks

.travis.yml
At least until CRL updates their package
=> [Do not merge] Allow BR2_BUILD_PIKSI_INS_REF build failures

.travis.yml
Reverts swift-nav/piksi_buildroot#652
=> Revert "Allow BR2_BUILD_PIKSI_INS_REF build failures"

package/fpga_error_moni/Config.in, package/fpga_error_moni/fpga_error_moni.mk, package/fpga_error_moni/src/Makefile, package/fpga_error_moni/src/fpga_error_moni.c
This needs to merge in the latest master in order to compile but I wanted to give the single commit on it's own to easily rebase or cherry-pick as you see fit. Or just copy-paste!
=> Port to new libpiksi loop/endpoint apis

package/piksi_system_daemon/src/main.c
Fixes system daemon not responding to command requests
=> [bugfix] ZMQ Refactor missed an attach in piksi system daemon

board/piksiv3/post_image.sh, board/piksiv3/rootfs-overlay/etc/init.d/S84failsafe_update, package/image_table_tool/src/image_table_tool.c, package/upgrade_tool/upgrade_tool.mk
Up for initial review, will fill in more details later.
See https://swift-nav.atlassian.net/browse/DEVC-709
=> Update the failsafe bootloader on start-up [DEVC-709]

package/fpga_error_moni/Config.in, package/fpga_error_moni/fpga_error_moni.mk, package/fpga_error_moni/src/Makefile, package/fpga_error_moni/src/fpga_error_moni.c
To fix NAP verification monitor (#641)
=> Port to new libpiksi loop/endpoint apis [round 2]

package/health_daemon/src/Makefile, package/health_daemon/src/health_daemon.c, package/health_daemon/src/ntrip_obs_monitor.c, package/health_daemon/src/ntrip_obs_monitor.h
=> [DEVC-426] Add warning if no base obs seen when ntrip is enabled [v1.6]

package/gnss_convertors/gnss_convertors.mk
Release update to suppress MSM unused obs
=> Update gnss-convertors to 0.3.50

board/piksiv3/rootfs-overlay/etc/init.d/S80endpoint_router_sbp, package/sbp_protocol/src/sbp_router_smoothpose.yml
=> Fix naming of "INS only" setting [v1.6]

package/gnss_convertors/gnss_convertors.mk
Pull in https://github.com/swift-nav/gnss-converters/pull/90
=> EX-206: point gnss_convertors to EX-206 fix branch

package/gnss_convertors/gnss_convertors.mk
Release version of https://github.com/swift-nav/piksi_buildroot/pull/691
=> [v16] EX-206: Update gnss_convertors to 0.3.51

board/piksiv3/patches/linux/0004-mtd-spi-nor-macronix-ear-read-write-support.patch
=> [DEVC-570] mtd driver to support macronix flash [v1.6]

package/gnss_convertors/gnss_convertors.mk, package/librtcm/librtcm.mk
Pulls in https://github.com/swift-nav/gnss-converters/pull/91 to fix week roll-over issues
=> EX-230: Update gnss-convertors time diff handling

package/health_daemon/src/health_daemon.c, package/health_daemon/src/skylark_monitor.c
=> Skylark health daemon valid file check [master] [DEVC-687]

package/health_daemon/src/health_daemon.c, package/health_daemon/src/skylark_monitor.c
RE: Core Dumps, this is in both 1.5 and 1.6 and might cause a fault
=> [DEVC-687] Skylark health daemon valid file check

package/piksi_system_daemon/overlay/etc/init.d/update_ntp_config
=> [DEVC-961] Replace ntpd monit call with init script call [v1.6]

package/piksi_system_daemon/overlay/etc/init.d/update_ntp_config
=> [DEVC-961] Replace ntpd monit call with init script call [master]

package/piksi_system_daemon/src/main.c
=> repeat msg_cmd_resp after upgrade

package/piksi_system_daemon/src/main.c
still awaiting testing in a real image.
=> fixup repeat sbp_cmd_resp PR

package/gnss_convertors/gnss_convertors.mk, package/librtcm/librtcm.mk, package/sbp_rtcm3_bridge/src/sbp.c, package/sbp_rtcm3_bridge/src/sbp.h, package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Pulls in https://github.com/swift-nav/gnss-converters/pull/102
=> EX-275: Update gnss_convertors for GLO timestamp fix

package/gnss_convertors/gnss_convertors.mk
Use gnss-converters release version
=> Update GNSS Converters version

package/upgrade_tool/upgrade_tool.mk
This should allow building without a GitHub account.
=> Download upgrade tool with https [DEVC-1043]

package/upgrade_tool/upgrade_tool.mk
=> Download upgrade tool with https [DEVC-1043] [master]

board/piksiv3/device_table.txt, package/common_init/overlay/etc/fstab, package/upgrade_tool/upgrade_tool.mk
=> Add upgrade_data dir for encrypted upgrades [DEVC-1055]

package/libpiksi/libpiksi/src/settings.c
Wrap settings signal handler to work for both signature types required by `util.h`
RE: https://swift-nav.atlassian.net/browse/DEVC-1059
=> [DEVC-1059] Modify settings signal handler setup to match api

package/common_init/overlay/etc/init.d/S86health_daemon, package/health_daemon/src/Makefile, package/health_daemon/src/gnss_time_monitor.c, package/health_daemon/src/gnss_time_monitor.h, package/health_daemon/src/health_daemon.c, package/health_daemon/src/ntrip_obs_monitor.c, package/libnetwork/src/libnetwork.c, package/libpiksi/libpiksi/include/libpiksi/util.h, package/libpiksi/libpiksi/src/util.c
Fix candidate for https://swift-nav.atlassian.net/browse/DEVC-982
=> [DEVC-982] Trigger NTRIP download only after GPS time is available

package/libpiksi/libpiksi/include/libpiksi/util.h, package/libpiksi/libpiksi/src/util.c, package/ntrip_daemon/src/ntrip_daemon.c, package/ntrip_daemon/src/ntrip_settings.c, package/ntrip_daemon/src/ntrip_settings.h
Fix for https://swift-nav.atlassian.net/browse/DEVC-686
=> [DEVC-686] Reject NTRIP settings while NTRIP is enabled

package/skylark_daemon/src/skylark_settings.c
See https://github.com/swift-nav/piksi_firmware_private/pull/2294
=> [DEVC-548] Move skylark.enable registration to PFWP and add watch trigger

package/common_init/overlay/etc/init.d/S18cfg, package/common_init/overlay/etc/init.d/S86piksi_leds, package/libpiksi/libpiksi/include/libpiksi/util.h, package/libpiksi/libpiksi/src/util.c, package/piksi_system_daemon/src/main.c
Moving these settings from PWFP:
https://swift-nav.atlassian.net/browse/DEVC-472
https://github.com/swift-nav/piksi_buildroot/pull/552#issuecomment-379345790
requires https://github.com/swift-nav/piksi_firmware_private/pull/2311
=> Moving hw_version and hw_revision to linux and adding product_id [DEVC-472]

package/grpc_custom/grpc_custom.mk
=> Trim gRPC make

package/common_init/overlay/etc/init.d/S18cfg, package/common_init/overlay/etc/init.d/copy_duro_eeprom.sh, package/libpiksi/libpiksi/src/util.c, package/piksi_system_daemon/src/main.c
per discussion amongst team.
This has been tested on bench to reduce boot time by a lot.
=> Do EEPROM copy in background [DEVC-1098]

package/common_init/overlay/etc/init.d/ifplugd.sh
https://swift-nav.atlassian.net/browse/DEVC-1065
=> [DEVC-1065][RELEASE] ifplugd: Remove -a option

package/common_init/overlay/etc/init.d/ifplugd.sh
https://swift-nav.atlassian.net/browse/DEVC-1065
=> [DEVC-1065][master] ifplugd: Remove -a option

board/piksiv3/rootfs-overlay/etc/init.d/S96piksi_ins, package/piksi_ins/overlay/etc/init.d/S96piksi_ins, package/piksi_ins/piksi_ins.mk
=> Dzollo/smoothpose init v2.1 rel

package/upgrade_tool/upgrade_tool.mk
This brings in: https://github.com/swift-nav/piksi_upgrade_tool/commit/49398b996c5effdc384a742f6a2fa09a70b80bb9
=> Update upgrade_tool to v2.1.6 [v2.1] [DEVC-1077]

package/upgrade_tool/upgrade_tool.mk
Master version of #855
https://github.com/swift-nav/piksi_upgrade_tool/commit/657febf43173c778b22f3da5f30d802c01cbefbe
=> Update upgrade_tool to v2.2.1 [DEVC-1077] 

package/librtcm/librtcm.mk
@pmiettinen @benjaminaltieri I hope this fixes the master build
=> Update librtcm to fix master build

package/ports_daemon/ports_daemon/src/whitelists.c
see master version for description #828
=> Remove IMU_RAW from UART1 default whitelist

package/libnetwork/src/libnetwork.c, package/libnetwork/src/libnetwork.h, package/ota_daemon/src/ota_daemon.c
https://swift-nav.atlassian.net/projects/DEVC/issues/DEVC-1141
=> [DEVC-1141] libnetwork: Add support for download/upload byte count and limit

package/ota_daemon/src/ota_daemon.c, package/ota_daemon/src/ota_settings.c, package/ota_daemon/src/ota_settings.h
https://swift-nav.atlassian.net/projects/DEVC/issues/DEVC-168
=> [DEVC-168] OTA: Add support for system.ota_debug and system.ota_url settings

package/librtcm/librtcm.mk
Pull in https://github.com/swift-nav/librtcm/pull/63
/cc @mbavaro
=> Update librtcm for ephemeris placeholder size fix [v2.1]

board/piksiv3/post_image.sh
* Pull specific build tools version
* Update post_image.sh
=> Pull specific build tools version [DEVC-1105]

fetch_firmware.sh, package/orion_daemon/src/orion_daemon.cc
To identify Orion sessions, we need to log out the unique incoming service uuid.
/cc @pgrgich
=> Orion: Log out unique incoming service uuid

package/standalone_file_logger/standalone_file_logger/src/standalone_file_logger.cc
=> Downgrading standalone logger daemon startup message [DEVC-1165]

package/sbp_fileio_daemon/sbp_fileio_daemon/src/sbp_fileio.c
Attempting to list a directory that does not exist results in a
readdir(NULL) call. This causes a core dump.
We now ignore any requests on non-existing directories
=> Fix core dump on fileio v2.1.0-release [DEVC-1138]

package/libpiksi/libpiksi/src/util.c
Updated file open type as append to ensure the new json data is append at the end of the file.
=> fix metrics_daemon file append issue [DEVC-1222]

package/gnss_convertors/gnss_convertors.mk
Pulls in https://github.com/swift-nav/gnss-converters/pull/151
=> EX-397, MAP-652: Update gnss-convertors for NMEA fixes [release]

package/gnss_convertors/gnss_convertors.mk
Pull in https://github.com/swift-nav/gnss-converters/pull/150
=> EX-397: Fix sending of NMEA GSA [master]

scripts/docker.mk
+ This merge bug causes image .bin files to not be synced to the host, fix it
=> Fixup merge bug for docker-sync support [DEVC-1173] [v2.1]

package/sbp_protocol/src/sbp_router.yml
=> Fix Broken Master Build: removing CAN destination filter to non-existent port

package/libpiksi/libpiksi/include/libpiksi/util.h, package/libpiksi/libpiksi/src/metrics.c, package/libpiksi/libpiksi/src/util.c, package/resource_monitor/resource_monitor/src/Makefile, package/resource_monitor/resource_monitor/src/extrace.c, package/resource_monitor/resource_monitor/src/query_cpu_usage.c, package/resource_monitor/resource_monitor/src/query_mem_usage.c, package/resource_monitor/resource_monitor/src/resource_monitor.c, package/resource_monitor/resource_monitor/src/resource_query.c, package/resource_monitor/resource_monitor/src/resource_query.h
=> Resolve some of the resource monitor noise [DEVC-1254]

README.md
=> Update readme to reflect current limitations in building from source [DEVC-1186][v2.0]

README.md
=> Update readme to reflect current limitations in building from source  [DEVC-1186][v2.1]

package/build_tools/build_tools.mk
https://github.com/swift-nav/piksi_upgrade_tool/compare/v2.2.4...v2.2.6
=> Update piksi_build_tools to v2.2.6

package/common_init/overlay/etc/init.d/gps_adapter.sh, package/endpoint_adapter/src/endpoint_adapter.c, package/endpoint_router/endpoint_router/src/endpoint_router.c, package/libpiksi/libpiksi/include/libpiksi/endpoint.h, package/libpiksi/libpiksi/src/endpoint.c
=> Add retry support to endpoint_adapter and endpoints [DEVC-1271] (#1000)

package/libswiftnav/libswiftnav.mk
Brings in the following changes: https://github.com/swift-nav/libswiftnav/compare/v0.1.3...v0.1.4
cc @kmdade
=> Bump libswiftnav to 0.1.4

package/gnss_convertors/gnss_convertors.mk, package/librtcm/librtcm.mk, package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Release version of https://github.com/swift-nav/piksi_buildroot/pull/1010
=> EX-445: Send receiver&antenna descriptors via RTCM out [release]

package/common_init/overlay/etc/init.d/S79runsvdir, package/common_init/overlay/etc/init.d/runsvdir-start
(v2.2 version of #1011)
* Make runit service setup blocking [ESD-886]
* Wait for runit to actually start too
=> Make setup of runit service dirs blocking [ESD-886] [v2.2]

package/metrics_daemon/metrics_daemon/src/metrics_daemon.c
Backport fix in master(commit 996b6b37fa17f2623adf71617f6ff9d230052bb6)
=> fix metrics mismatch issue as described in [ESD-899]

package/piksi_ins_ref/piksi_ins_ref.mk
Brings in fixes to retry hardware challenge
=> Update piksi_ins_ref to latest [ME-108]

package/gnss_convertors/gnss_convertors.mk, package/librtcm/librtcm.mk, package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
Release version of https://github.com/swift-nav/piksi_buildroot/pull/1035
=> EX-472: Reject invalid RTCM antenna height setting values [release]

package/common_init/overlay/etc/init.d/S01reboot_logger, package/piksi_system_daemon/overlay/etc/init.d/do_sbp_msg_reset
Master port of  #1037
* Add script to send SBP for normal reboot
* Manually invoke in SBP reboot handler
=> Reboot logging [ESD-951] [ESD-943]

Makefile
=> Merge cherry-picks from refs/heads/v2.2.0-release (c45c58eb2) into master: Add `show-startup-order` make target [ESD-968] (#1070)

package/common_init/overlay/etc/init.d/S79runsvdir
=> Merge cherry-picks from refs/heads/v2.2.0-release (2e369d565) into master: Fix creation of service dir links [ESD-968] (#1072)

package/common_init/overlay/etc/init.d/common.sh, package/common_init/overlay/etc/init.d/logging.sh, package/common_init/overlay/etc/init.d/template_runsv.inc.sh, package/common_init/overlay/usr/bin/service_stopped, package/common_init/overlay/usr/bin/start_service
Manual backport of #1008 to v2.2, PR does not need to go to master.
As part of ESD-968 (ip challenge hangs in PoseDaemon) one of the workarounds was to allow the PoseDaemon to exit if the ip-challenge fails so that it can be restarted to try again.  This change allows the PoseDaemon to restart without worrying about being restarted indefinitely.
+ Stop restarting after 10 failed restarts
+ If a service fails to restart 10 times (consecutively), don't continue
to try to restart it
+ Detect if the service is restarting too quickly
=> Stop restarting after 10 failed restarts [ESD-654] [ESD-968]

board/piksiv3/rootfs-overlay/etc/init.d/S85piksi_firmware, package/common_init/overlay/etc/init.d/S01reboot_logger, package/common_init/overlay/etc/init.d/S80endpoint_router_sbp, package/common_init/overlay/etc/init.d/S95watchdog_disable, package/common_init/overlay/etc/init.d/common.sh, package/piksi_ins/overlay/etc/init.d/S96piksi_ins, package/piksi_ins/overlay/etc/init.d/S96piksi_ins_monitor, package/piksi_ins/overlay/usr/bin/pose_daemon_monitor, package/piksi_ins/overlay/usr/bin/start_pose_daemon, package/piksi_ins/piksi_ins.mk, package/piksi_ins_ref/piksi_ins_ref.mk
=> Merge cherry-picks from refs/heads/v2.2.0-release (bc002f840) into master: Add pose_daemon monitor script [ESD-968] [3/3]

package/libpiksi/libpiksi/src/endpoint.c, package/libpiksi/libpiksi/src/sbp_rx.c, package/resource_monitor/resource_monitor/src/sbp.c, package/sbp_protocol/src/sbp_router.yml, package/sbp_protocol/src/sbp_router_smoothpose.yml, package/starling_daemon/overlay/etc/endpoint_router/sbp_router_starling.yml
=> Merge cherry-picks from refs/heads/v2.2.0-release (a0da72eff) into master: Reconnect in sbp_rx if we get disconnected [ESD-968] (#1069)

package/libsettings/libsettings.mk, package/sbp_settings_daemon/sbp_settings_daemon/src/settings.c
Requires https://github.com/swift-nav/libsettings/pull/5
Sync with https://github.com/swift-nav/piksi_firmware_private/pull/2592
=> Align settings write response with specification [ESD-966] [ESD-971]

package/standalone_file_logger/standalone_file_logger/src/standalone_file_logger.cc
Related to #1096, this ports the reconnect logic from `sbp_rx` to `standalone_file_logger` to allow logging to recover in case of an overflow in the rx queue.
In this case to mimic `sbp_rx`, we stuff the `pk_endpoint` context, the reader handle and endpoint name into it's own context that's used to reattach (`detach`, `destroy`, `create` and `attach`) to the proper underlying uds socket. This has the opportunity to be folded into `libpiksi` as a pattern but for now I am simply reproducing and applying it.
=> Allow standalone logger to handle endpoint disconnects  [ESD-981] [ESD-988]

package/common_init/overlay/etc/init.d/common.sh, package/common_init/overlay/etc/init.d/copy_sys_logs.sh, package/common_init/overlay/etc/init.d/migrate_sdcard.sh, package/common_init/overlay/etc/init.d/sdcard.sh, package/common_init/overlay/lib/mdev/automount.sh, package/common_init/overlay/usr/bin/service_stopped, package/common_init/overlay/usr/bin/start_service, package/standalone_file_logger/standalone_file_logger/src/rotating_logger.cc
=> Merge cherry-picks from refs/heads/v2.2.0-release (81865eb9e) into master: Allow standalone logging to create files in  F2FS mode [ESD-1005] (#1102)

package/common_init/overlay/etc/init.d/common.sh
=> Merge cherry-picks from refs/heads/v2.2.0-release (52ad0aec5) into master: Use PoseDaemon.enc to verify that PoseDaemon exists on device (#1114)

scripts/aws-setup.mk
=> Merge cherry-picks from refs/heads/v2.2.0-release (22437c40a) into master: aws s3 cp; try --no-sign-request if initial cp fails (#1121)

package/sbp_settings_daemon/sbp_settings_daemon/src/settings.c
If needed, this can be used to revive master branch settings functionality meanwhile longer term fixes are worked on.
https://swift-nav.atlassian.net/projects/ESD/issues/ESD-1000
=> Hotfix for settings write reply [ESD-1000]

package/gnss_convertors/gnss_convertors.mk
Pull in https://github.com/swift-nav/gnss-converters/pull/166
=> EX-499, EX-501: fix GLO TOW rounding in RTCM-SBP converter

package/libsettings/libsettings.mk, package/sbp_settings_daemon/sbp_settings_daemon/src/settings.c
https://github.com/swift-nav/libsettings/pull/6
Shall be updated alongside https://github.com/swift-nav/piksi_firmware_private/pull/2634
=> Use settings format utility from libsettings [ESD-992]

package/standalone_file_logger/standalone_file_logger/src/Makefile, package/standalone_file_logger/standalone_file_logger/src/rotating_logger.cc, package/standalone_file_logger/standalone_file_logger/src/rotating_logger.h, package/standalone_file_logger/standalone_file_logger/src/standalone_file_logger.cc, package/standalone_file_logger/standalone_file_logger/test/run_rotating_logger_test.cc
=> Merge cherry-picks from refs/heads/v2.2.0-release (d74fd3f0c) into master: Fix standalone logging crash [ESD-981] (#1096)

package/gnss_convertors/gnss_convertors.mk
Pull in https://github.com/swift-nav/gnss-converters/pull/168.
Fixes https://swift-nav.atlassian.net/browse/STAR-395.
=> EX-515: Update gnss-converters to timestamp rounding fix

package/libsettings/libsettings.mk, package/sbp_settings_daemon/sbp_settings_daemon/src/settings.c, package/sbp_settings_daemon/sbp_settings_daemon/test/run_sbp_settings_daemon_test.cc
https://github.com/swift-nav/libsettings/pull/9
=> Use SETTINGS_BUFLEN [ESD-1028]

package/libpiksi/libpiksi/src/util.c
=> Merge cherry-picks from refs/heads/v2.2.0-release (1a16980e5) into master: Use encrypted PoseDaemon filepath to determine whether it exists (#1136)

package/resource_monitor/resource_monitor/src/Makefile
Removing the regression identified in [this comment](https://swift-nav.atlassian.net/browse/STAR-444?focusedCommentId=20849&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-20849). Changes were introduced in #999. Will need to root cause CPU issues before re-enabling
=> Remove fd queries for now [ESD-1102] [ESD-1101]

package/gnss_convertors/gnss_convertors.mk, package/sbp_nmea_bridge/src/sbp_nmea_bridge.c
Pull in the `sbp2nmea` rework in https://github.com/swift-nav/gnss-converters/pull/153 and adapt to the updated API.
Correct NMEA output tested on bench.
=> EX-534: sbp2nmea rework

.travis.yml, Makefile, board/piksiv3/post_image.sh, fetch_firmware.sh, fetch_firmware.sh.m4, package/piksi_ins/piksi_ins.mk, scripts/Dockerfile.sdk, scripts/need_tag_artifacts.sh, scripts/travis.sh
Creates a build variant which for an "SDK image" which contains SSH access, but no INS, and no image encryption (and no ability to decrypt protected images).
=> SDK image build variant [ESD-243]

package/gnss_convertors/gnss_convertors.mk, package/sbp_nmea_bridge/src/sbp_nmea_bridge.c
Bring in an updated gnss-converters and enable the GST message
@benjaminaltieri
=> Enable NMEA GST message support

package/sbp_rtcm3_bridge/src/sbp_rtcm3_bridge.c
This PR updates sbp_rtcm3_bridge to treat it's pub and sub sockets the same.
=> destroy both endpoints in sbp_rtcm3_bridge [ESD-1183]

package/cell_modem_daemon/src/cell_modem_daemon.c
This avoids log messages where the cell_modem_daemon gets disconnected
because it's not processing sbp messages fast enough.
=> Cell modem daemon doesn't need to receive data [ESD-1206]

package/gnss_convertors/gnss_convertors.mk, package/libsbp/libsbp.mk, package/sbp_nmea_bridge/src/sbp_nmea_bridge.c, package/sbp_protocol/src/sbp_router.yml, package/sbp_protocol/src/sbp_router_smoothpose.yml
Pull in `gnss-converters` tagged branch including https://github.com/swift-nav/gnss-converters/pull/180 
Pending `libsbp` master tag to include https://github.com/swift-nav/libsbp/pull/670
NMEA output from the PR:
```
$GPZDA,113556.00,28,03,2019,,*60
$GPGSV,3,1,10,01,16,020,41,06,03,126,42,10,12,292,43,12,36,242,50*76
$GPGSV,3,2,10,13,03,174,39,15,20,202,48,17,49,076,48,19,54,118,48*71
$GPGSV,3,3,10,24,72,232,51,28,15,072,41*72
$GLGSV,3,1,09,67,14,232,43,68,37,288,48,69,23,344,46,76,26,098,45*60
$GLGSV,3,2,09,77,86,346,45,78,33,282,49,85,17,016,42,86,50,076,47*6A
$GLGSV,3,3,09,87,25,148,48*55
$GAGSV,2,1,07,301,06,090,36,303,30,308,44,305,31,248,44,324,66,254,49*6D
$GAGSV,2,2,07,325,13,266,43,326,27,040,43,331,55,098,47*6E
$GBGSV,3,1,09,408,35,076,42,413,28,104,43,414,23,288,43,421,08,242,4 …
```
=> ESD-1180: Support NMEA GSV generation in gnss-converters

scripts/travis.sh
=> Merge cherry-picks from refs/heads/v2.3.0-release (0216d774a) into master: Correct name of toolchain export target [ESD-1207] (#1213)

package/libpiksi/libpiksi/src/settings_client.c, package/libsettings/Config.in, package/libsettings/libsettings.mk, package/libswiftnav/libswiftnav.mk
Test and integrate https://github.com/swift-nav/libsettings/pull/27
UPDATE: update straight to libsettings-v0.1.11
=> libsettings with LSN as library [ESD-1116]

package/gnss_convertors/gnss_convertors.mk
=> Merge cherry-picks from refs/heads/v2.3.0-release (2785802ac) into master: Update gnss-convertors for GST fixes (#1232)

package/health_daemon/src/baseline_monitor.c
=> Merge cherry-picks from refs/heads/v2.3.0-release (b2e57a130) into master: Update baseline threshold warning (#1229)

package/libsettings/libsettings.mk, package/sbp_settings_daemon/sbp_settings_daemon/src/settings_sbp_cb.c
Requires https://github.com/swift-nav/libsettings/pull/26/
=> Settings watcher false alarms on boot [ESD-1049]

Jenkinsfile
=> Merge cherry-picks from refs/heads/v2.3.0-release (cacf70fbc) into master: Try to fix Jenkins SDK build logic (#1252)

scripts/release-post-tag
=> Merge cherry-picks from refs/heads/v2.3.0-release (edd906dca) into master: Support NO_WRITE in the release post tag script

Jenkinsfile
=> Merge cherry-picks from refs/heads/v2.3.0-release (088117e35) into master: Use gitHeadHasTag to gate SDK build

package/gnss_convertors/gnss_convertors.mk, package/librtcm/librtcm.mk, package/libsbp/libsbp.mk
Brings in the following changesets:
https://github.com/swift-nav/gnss-converters/compare/v0.3.81...v0.3.83
https://github.com/swift-nav/librtcm/compare/v0.2.38...v0.2.41
https://github.com/swift-nav/libsbp/compare/v2.5.1...v2.5.5
=> Update gnss converters

package/piksi_system_daemon/src/main.c
=> Merge cherry-picks from refs/heads/v2.3.0-release (2f4a0139b) into master: Add ethernet:interface_mode setting [ESD-1320] (#1247)

package/sample_daemon/src/sample_daemon.c
As part of the build variant / binary artifact support for piksi_buildroot we enabled the "sample daemon" in the internal build so that we don't have to have a whole separate "SDK" build just to verify that the sample daemon builds. This cause the sample daemon to show up in the internal build and start logging things.  We'll continue to include sample daemon in the internal build, but we fix this by adding a setting to disable the sample daemon operation under normal circumstances.
=> Add a settings to disable the sample daemon by default [ESD-1341]

package/sample_daemon/src/sample_daemon.c
=> Merge cherry-picks from refs/heads/v2.3.0-release (0b284f105) into master: Add a settings to disable the sample daemon by default

board/piksiv3/post_image.sh
Found while helping @acer with #1287.
=> Fix-ups for post_image to handle whitespace gracefully

package/ports_daemon/ports_daemon/src/whitelists.c
Update Galileo ephemeris msg type and Skylark OSR message
=> Update Default message whitelist in buildroot

Jenkinsfile
same as https://github.com/swift-nav/piksi_buildroot_private/pull/42
=> re-introduce requirements.yaml for nonPR builds

board/piksiv3/post_build.sh, package/piksi_system_daemon/overlay/etc/build_variant, package/piksi_system_daemon/src/main.c
=> Add build variant setting [ESD-1707] [INFRA-52] [v2.3]
